SELECT
	P.ABS_BIRTH_DT_TM
	, P.ACTIVE_IND
	, P_ACTIVE_STATUS_DISP = UAR_GET_CODE_DISPLAY(P.ACTIVE_STATUS_CD)
	, P.ACTIVE_STATUS_DT_TM
	, P.ACTIVE_STATUS_PRSNL_ID
	, P.AGE_AT_DEATH
	, P.AGE_AT_DEATH_PREC_MOD_FLAG
	, P_AGE_AT_DEATH_UNIT_DISP = UAR_GET_CODE_DISPLAY(P.AGE_AT_DEATH_UNIT_CD)
	, P.ARCHIVE_ENV_ID
	, P_ARCHIVE_STATUS_DISP = UAR_GET_CODE_DISPLAY(P.ARCHIVE_STATUS_CD)
	, P.ARCHIVE_STATUS_DT_TM
	, P_AUTOPSY_DISP = UAR_GET_CODE_DISPLAY(P.AUTOPSY_CD)
	, P.BEG_EFFECTIVE_DT_TM
	, P_BIRTH_DT_DISP = UAR_GET_CODE_DISPLAY(P.BIRTH_DT_CD)
	, P.BIRTH_DT_TM
	, P.BIRTH_PREC_FLAG
	, P.BIRTH_TZ
	, P.CAUSE_OF_DEATH
	, P_CAUSE_OF_DEATH_DISP = UAR_GET_CODE_DISPLAY(P.CAUSE_OF_DEATH_CD)
	, P_CITIZENSHIP_DISP = UAR_GET_CODE_DISPLAY(P.CITIZENSHIP_CD)
	, P.CONCEPTION_DT_TM
	, P_CONFID_LEVEL_DISP = UAR_GET_CODE_DISPLAY(P.CONFID_LEVEL_CD)
	, P_CONTRIBUTOR_SYSTEM_DISP = UAR_GET_CODE_DISPLAY(P.CONTRIBUTOR_SYSTEM_CD)
	, P.CREATE_DT_TM
	, P.CREATE_PRSNL_ID
	, P_DATA_STATUS_DISP = UAR_GET_CODE_DISPLAY(P.DATA_STATUS_CD)
	, P.DATA_STATUS_DT_TM
	, P.DATA_STATUS_PRSNL_ID
	, P_DECEASED_DISP = UAR_GET_CODE_DISPLAY(P.DECEASED_CD)
	, P.DECEASED_DT_TM
	, P.DECEASED_DT_TM_PREC_FLAG
	, P_DECEASED_ID_METHOD_DISP = UAR_GET_CODE_DISPLAY(P.DECEASED_ID_METHOD_CD)
	, P_DECEASED_NOTIFY_SOURCE_DISP = UAR_GET_CODE_DISPLAY(P.DECEASED_NOTIFY_SOURCE_CD)
	, P_DECEASED_SOURCE_DISP = UAR_GET_CODE_DISPLAY(P.DECEASED_SOURCE_CD)
	, P.DECEASED_TZ
	, P.EMANCIPATION_DT_TM
	, P.END_EFFECTIVE_DT_TM
	, P_ETHNIC_GRP_DISP = UAR_GET_CODE_DISPLAY(P.ETHNIC_GRP_CD)
	, P.FT_ENTITY_ID
	, P.FT_ENTITY_NAME
	, P_LANGUAGE_DISP = UAR_GET_CODE_DISPLAY(P.LANGUAGE_CD)
	, P_LANGUAGE_DIALECT_DISP = UAR_GET_CODE_DISPLAY(P.LANGUAGE_DIALECT_CD)
	, P.LAST_ACCESSED_DT_TM
	, P.LAST_ENCNTR_DT_TM
	, P.LOGICAL_DOMAIN_ID
	, P_MARITAL_TYPE_DISP = UAR_GET_CODE_DISPLAY(P.MARITAL_TYPE_CD)
	, P.MILITARY_BASE_LOCATION
	, P_MILITARY_RANK_DISP = UAR_GET_CODE_DISPLAY(P.MILITARY_RANK_CD)
	, P_MILITARY_SERVICE_DISP = UAR_GET_CODE_DISPLAY(P.MILITARY_SERVICE_CD)
	, P.MOTHER_MAIDEN_NAME
	, P.NAME_FIRST
	, P.NAME_FIRST_KEY
	, P.NAME_FIRST_KEY_A_NLS
	, P.NAME_FIRST_KEY_NLS
	, P.NAME_FIRST_PHONETIC
	, P.NAME_FIRST_SYNONYM_ID
	, P.NAME_FULL_FORMATTED
	, P.NAME_LAST
	, P.NAME_LAST_KEY
	, P.NAME_LAST_KEY_A_NLS
	, P.NAME_LAST_KEY_NLS
	, P.NAME_LAST_PHONETIC
	, P.NAME_MIDDLE
	, P.NAME_MIDDLE_KEY
	, P.NAME_MIDDLE_KEY_A_NLS
	, P.NAME_MIDDLE_KEY_NLS
	, P.NAME_PHONETIC
	, P_NATIONALITY_DISP = UAR_GET_CODE_DISPLAY(P.NATIONALITY_CD)
	, P.NEXT_RESTORE_DT_TM
	, P.PERSON_ID
	, P_PERSON_STATUS_DISP = UAR_GET_CODE_DISPLAY(P.PERSON_STATUS_CD)
	, P_PERSON_TYPE_DISP = UAR_GET_CODE_DISPLAY(P.PERSON_TYPE_CD)
	, P_PURGE_OPTION_DISP = UAR_GET_CODE_DISPLAY(P.PURGE_OPTION_CD)
	, P_RACE_DISP = UAR_GET_CODE_DISPLAY(P.RACE_CD)
	, P_RELIGION_DISP = UAR_GET_CODE_DISPLAY(P.RELIGION_CD)
	, P_RESIDENT_DISP = UAR_GET_CODE_DISPLAY(P.RESIDENT_CD)
	, P.ROWID
	, P.SEX_AGE_CHANGE_IND
	, P_SEX_DISP = UAR_GET_CODE_DISPLAY(P.SEX_CD)
	, P_SPECIES_DISP = UAR_GET_CODE_DISPLAY(P.SPECIES_CD)
	, P.UPDT_APPLCTX
	, P.UPDT_CNT
	, P.UPDT_DT_TM
	, P.UPDT_ID
	, P.UPDT_TASK
	, P_VET_MILITARY_STATUS_DISP = UAR_GET_CODE_DISPLAY(P.VET_MILITARY_STATUS_CD)
	, P_VIP_DISP = UAR_GET_CODE_DISPLAY(P.VIP_CD)
	, PR.ACTIVE_IND
	, PR_ACTIVE_STATUS_DISP = UAR_GET_CODE_DISPLAY(PR.ACTIVE_STATUS_CD)
	, PR.ACTIVE_STATUS_DT_TM
	, PR.ACTIVE_STATUS_PRSNL_ID
	, PR.BEG_EFFECTIVE_DT_TM
	, PR_CONTRIBUTOR_SYSTEM_DISP = UAR_GET_CODE_DISPLAY(PR.CONTRIBUTOR_SYSTEM_CD)
	, PR.CREATE_DT_TM
	, PR.CREATE_PRSNL_ID
	, PR_DATA_STATUS_DISP = UAR_GET_CODE_DISPLAY(PR.DATA_STATUS_CD)
	, PR.DATA_STATUS_DT_TM
	, PR.DATA_STATUS_PRSNL_ID
	, PR_DEPARTMENT_DISP = UAR_GET_CODE_DISPLAY(PR.DEPARTMENT_CD)
	, PR.EMAIL
	, PR.END_EFFECTIVE_DT_TM
	, PR.EXTERNAL_IND
	, PR.FREE_TEXT_IND
	, PR.FT_ENTITY_ID
	, PR.FT_ENTITY_NAME
	, PR.LOGICAL_DOMAIN_GRP_ID
	, PR.LOGICAL_DOMAIN_ID
	, PR.LOG_ACCESS_IND
	, PR.LOG_LEVEL
	, PR.NAME_FIRST
	, PR.NAME_FIRST_KEY
	, PR.NAME_FIRST_KEY_A_NLS
	, PR.NAME_FIRST_KEY_NLS
	, PR.NAME_FULL_FORMATTED
	, PR.NAME_LAST
	, PR.NAME_LAST_KEY
	, PR.NAME_LAST_KEY_A_NLS
	, PR.NAME_LAST_KEY_NLS
	, PR.PASSWORD
	, PR.PERSON_ID
	, PR.PHYSICIAN_IND
	, PR_PHYSICIAN_STATUS_DISP = UAR_GET_CODE_DISPLAY(PR.PHYSICIAN_STATUS_CD)
	, PR_POSITION_DISP = UAR_GET_CODE_DISPLAY(PR.POSITION_CD)
	, PR_PRIM_ASSIGN_LOC_DISP = UAR_GET_CODE_DISPLAY(PR.PRIM_ASSIGN_LOC_CD)
	, PR_PRSNL_TYPE_DISP = UAR_GET_CODE_DISPLAY(PR.PRSNL_TYPE_CD)
	, PR.ROWID
	, PR_SECTION_DISP = UAR_GET_CODE_DISPLAY(PR.SECTION_CD)
	, PR.UPDT_APPLCTX
	, PR.UPDT_CNT
	, PR.UPDT_DT_TM
	, PR.UPDT_ID
	, PR.UPDT_TASK
	, PR.USERNAME

FROM
	PERSON   P
	, (INNER JOIN PRSNL PR ON (PR.PERSON_ID = P.PERSON_ID))

WHERE
	P.PERSON_ID = 11659304 ; generic control doctor
	OR
	P.PERSON_ID = 11652489 ; generic control doctor
	OR
	P.PERSON_ID = ; insert Id of doctor you want to compare to

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10