SELECT
	C.ACCESSION_NBR
	, C.AUTHENTIC_FLAG
	, C_CATALOG_DISP = UAR_GET_CODE_DISPLAY(C.CATALOG_CD)
	, C.CE_DYNAMIC_LABEL_ID
	, C.CLINICAL_EVENT_ID
	, C.CLINICAL_SEQ
	, C.CLINSIG_UPDT_DT_TM
	, C.COLLATING_SEQ
	, C_CONTRIBUTOR_SYSTEM_DISP = UAR_GET_CODE_DISPLAY(C.CONTRIBUTOR_SYSTEM_CD)
	, C.CRITICAL_HIGH
	, C.CRITICAL_LOW
	, C.DEVICE_FREE_TXT
	, C.ENCNTR_FINANCIAL_ID
	, C.ENCNTR_ID
	, C_ENTRY_MODE_DISP = UAR_GET_CODE_DISPLAY(C.ENTRY_MODE_CD)
	, C_EVENT_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_CD)
	, C_EVENT_CLASS_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_CLASS_CD)
	, C.EVENT_END_DT_TM
	, C.EVENT_END_DT_TM_OS
	, C.EVENT_END_TZ
	, C.EVENT_ID
	, C_EVENT_RELTN_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_RELTN_CD)
	, C.EVENT_START_DT_TM
	, C.EVENT_START_TZ
	, C.EVENT_TAG
	, C.EVENT_TAG_SET_FLAG
	, C.EVENT_TITLE_TEXT
	, C.EXPIRATION_DT_TM
	, C_INQUIRE_SECURITY_DISP = UAR_GET_CODE_DISPLAY(C.INQUIRE_SECURITY_CD)
	, C.MODIFIER_LONG_TEXT_ID
	, C.NOMEN_STRING_FLAG
	, C_NORMALCY_DISP = UAR_GET_CODE_DISPLAY(C.NORMALCY_CD)
	, C_NORMALCY_METHOD_DISP = UAR_GET_CODE_DISPLAY(C.NORMALCY_METHOD_CD)
	, C.NORMAL_HIGH
	, C.NORMAL_LOW
	, C.NORMAL_REF_RANGE_TXT
	, C.NOTE_IMPORTANCE_BIT_MAP
	, C.ORDER_ACTION_SEQUENCE
	, C.ORDER_ID
	, C.PARENT_EVENT_ID
	, C.PERFORMED_DT_TM
	, C.PERFORMED_PRSNL_ID
	, C.PERFORMED_TZ
	, C.PERSON_ID
	, C.PUBLISH_FLAG
	, C_QC_REVIEW_DISP = UAR_GET_CODE_DISPLAY(C.QC_REVIEW_CD)
	, C_RECORD_STATUS_DISP = UAR_GET_CODE_DISPLAY(C.RECORD_STATUS_CD)
	, C.REFERENCE_NBR
	, C_RESOURCE_DISP = UAR_GET_CODE_DISPLAY(C.RESOURCE_CD)
	, C_RESOURCE_GROUP_DISP = UAR_GET_CODE_DISPLAY(C.RESOURCE_GROUP_CD)
	, C_RESULT_STATUS_DISP = UAR_GET_CODE_DISPLAY(C.RESULT_STATUS_CD)
	, C_RESULT_TIME_UNITS_DISP = UAR_GET_CODE_DISPLAY(C.RESULT_TIME_UNITS_CD)
	, C_RESULT_UNITS_DISP = UAR_GET_CODE_DISPLAY(C.RESULT_UNITS_CD)
	, C.RESULT_VAL
	, C.ROWID
	, C.SERIES_REF_NBR
	, C_SOURCE_DISP = UAR_GET_CODE_DISPLAY(C.SOURCE_CD)
	, C.SRC_CLINSIG_UPDT_DT_TM
	, C.SRC_EVENT_ID
	, C.SUBTABLE_BIT_MAP
	, C_TASK_ASSAY_DISP = UAR_GET_CODE_DISPLAY(C.TASK_ASSAY_CD)
	, C.TASK_ASSAY_VERSION_NBR
	, C.TRAIT_BIT_MAP
	, C.UPDT_APPLCTX
	, C.UPDT_CNT
	, C.UPDT_DT_TM
	, C.UPDT_ID
	, C.UPDT_TASK
	, C.VALID_FROM_DT_TM
	, C.VALID_UNTIL_DT_TM
	, C.VERIFIED_DT_TM
	, C.VERIFIED_PRSNL_ID
	, C.VERIFIED_TZ
	, C.VIEW_LEVEL

FROM
	CLINICAL_EVENT   C

WHERE C.EVENT_START_DT_TM
	C.EVENT_START_DT_TM >= CNVTDATETIME("31-FEB-2021 00:00:00.00")
	AND
	C.EVENT_START_DT_TM <= CNVTDATETIME("31-JUL-2021 23:59:59.00")

WITH MAXREC = 5000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 300