SELECT DISTINCT
	O.ORDER_ID
	, DT_COMPLETED = O.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, DT_COMPLETED_YEAR = O.UPDT_DT_TM "YYYY;;D"
	, DT_COMPLETED_MONTH = O.UPDT_DT_TM "MM;;D"
	, DT_COMPLETED_DAY = O.UPDT_DT_TM "DD;;D"
	, DT_COMPLETED_TIME = O.UPDT_DT_TM "HH:MM:SS;;D"
;	, DT_ORDERED = O.ORIG_ORDER_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
;	, CATALOG_TYPE = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD) ; Eg "Pharmacy Orders"
;	, ORDER_STATUS = UAR_GET_CODE_DISPLAY(O.ORDER_STATUS_CD) ; Eg "Completed"
	, SOURCE_APP = EVALUATE(
		MAE.SOURCE_APPLICATION_FLAG
		, 0, "Default - no value"
		, 1, "Care Mobil"
		, 2, "MAW (Care Admin in DB)"
		, 3, "MAR (PowerChart in DB)"
		)
;	, MED_TYPE = UAR_GET_CODE_DISPLAY(O.MED_ORDER_TYPE_CD)
	, ORDERED = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
;	, O.ORDER_MNEMONIC
;	, O.ORDERED_AS_MNEMONIC
;	, ORDER_DETAIL = O.ORDER_DETAIL_DISPLAY_LINE
	, STAFF = PR.NAME_FULL_FORMATTED
;	, PATIENT = P.NAME_FULL_FORMATTED
;	, URN = PA.ALIAS
;	, AH_ORDER_FLAG = EVALUATE(
;		O.AD_HOC_ORDER_FLAG
;		, 0,"Not ad hoc"
;		, 1,"Ad hoc via Bridge Interface"
;		, 2,"Ad hoc with completed order and task via Cerner Solutions"
;		, 3,"Adhoc Order with pending task and order in ordered status vi"
;		)
	, E_LOC_NURSE_UNIT_DISP = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
	, E_MED_SERVICE_DISP = UAR_GET_CODE_DISPLAY(E.MED_SERVICE_CD)
	, SCANNED = MAE.POSITIVE_PATIENT_IDENT_IND
	, NO_SCAN_REASON = UAR_GET_CODE_DISPLAY(MAPE.REASON_CD)

FROM
	ORDERS   O
;	, PERSON   P
;	, PERSON_ALIAS	PA
	, PRSNL   PR
	, MED_ADMIN_EVENT   MAE
	, ENCOUNTER   E
;	, MED_ADMIN_MED_ERROR   MAME
	, MED_ADMIN_ALERT   MAA
	, MED_ADMIN_PT_ERROR   MAPE


PLAN O
	WHERE 
		O.CATALOG_TYPE_CD =2516 ;Pharmacy Orders
		AND 
		O.ORDER_STATUS_CD = 2543 ; Completed Orders
		AND
		O.UPDT_DT_TM  ; Time Restriction
		BETWEEN
        	CNVTDATETIME("31-AUG-2022 00:00:00.00")
        	AND
			CNVTDATETIME("31-AUG-2022 12:00:00.00")
		AND
		O.ACTIVE_IND = 1
		AND
		O.ACTIVE_STATUS_CD = 188; "active"
;		AND
;		O.PERSON_ID = 12921277 ; limit by patient 12921277 is "TESTHTS, Joanne"

;JOIN PA WHERE PA.PERSON_ID = O.PERSON_ID ; To get patients URN
; 	AND
; 	PA.ALIAS_POOL_CD = 9569589 ;UR Numbers Only

;JOIN P WHERE P.PERSON_ID = O.PERSON_ID ; this does not seem to get the person completing the order when linking to updt_id

JOIN MAE WHERE MAE.ORDER_ID = O.ORDER_ID
;	; Med Admin (MAW) Only (which indicates the MAW)
;	AND
;	MAE.SOURCE_APPLICATION_FLAG = 2
;	AND
;	MAE.PRSNL_ID = 12876451


JOIN E WHERE E.ENCNTR_ID = O.ENCNTR_ID

JOIN PR WHERE PR.PERSON_ID = MAE.PRSNL_ID ; To get completing staff member

;JOIN MAME WHERE MAME.EVENT_ID = MAE.EVENT_ID

;OUTERJOIN
JOIN MAA WHERE MAA.MED_ADMIN_EVENT_ID = OUTERJOIN(MAE.MED_ADMIN_EVENT_ID)

JOIN MAPE WHERE MAPE.MED_ADMIN_ALERT_ID = MAA.MED_ADMIN_ALERT_ID

ORDER BY	
	O.UPDT_DT_TM   DESC
	, O.ORDER_ID   DESC
	, MAE.EVENT_ID   DESC
	, 0

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10

/*
NOTES

ORDER COMPLETE CONVERSIONS
CARE ADMIN = MAW
Powerchart = MAR

NO SCAN REASONS
Emergency
Malfunctioning Scann
No Scanner Available
Other
Patient Could nNot Be Identified
Patient Refused Scanning
Patient Under Contant Precautions
Unable to Scan Barcode
Unsafe to Scan

CODE SET
4003287

STORED IN TABLE
MED_ADMIN_PT_ERROR

July 2019 MAW went active


JOINS
MED_ADMIN_PT_ERROR	MAPE
MED_ADMIN_ALERT_ID
MED_ADMIN_ALERT		MAA
MED_ADMIN_EVENT_ID
MED_ADMIN_EVENT		MAE
ORDER_ID
ORDERS   			O
ENCNTR_ID
ENCOUNTER   		E


example updaters Ann,Adrain,Rachel,Annie; 11659304,13975953,11658813,12876451

 */ 
