UPDATE INTO PRSNL_ALIAS P_A
SET
    P_A.PERSON_ID = 13168395;newid moving to
    , P_A.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , P_A.UPDT_ID = REQINFO->UPDT_ID
    , P_A.UPDT_CNT = P_A.UPDT_CNT + 1

WHERE
; for this user
        P_A.PERSON_ID = 13215666; Old id that the alias are currently in


/* PRE CHECKER
    SELECT
        P_A.ACTIVE_IND
        , P_ACTIVE_STATUS_DISP = UAR_GET_CODE_DISPLAY(P_A.ACTIVE_STATUS_CD)
        , P_A.ACTIVE_STATUS_DT_TM
        , P_A.ACTIVE_STATUS_PRSNL_ID
        , P_A.ALIAS
        , P_ALIAS_POOL_DISP = UAR_GET_CODE_DISPLAY(P_A.ALIAS_POOL_CD)
        , P_A.BEG_EFFECTIVE_DT_TM
        , P_A.CHECK_DIGIT
        , P_CHECK_DIGIT_METHOD_DISP = UAR_GET_CODE_DISPLAY(P_A.CHECK_DIGIT_METHOD_CD)
        , P_CONTRIBUTOR_SYSTEM_DISP = UAR_GET_CODE_DISPLAY(P_A.CONTRIBUTOR_SYSTEM_CD)
        , P_DATA_STATUS_DISP = UAR_GET_CODE_DISPLAY(P_A.DATA_STATUS_CD)
        , P_A.DATA_STATUS_DT_TM
        , P_A.DATA_STATUS_PRSNL_ID
        , P_A.END_EFFECTIVE_DT_TM
        , P_A.PERSON_ID
        , P_A.PRSNL_ALIAS_ID
        , P_PRSNL_ALIAS_SUB_TYPE_DISP = UAR_GET_CODE_DISPLAY(P_A.PRSNL_ALIAS_SUB_TYPE_CD)
        , P_PRSNL_ALIAS_TYPE_DISP = UAR_GET_CODE_DISPLAY(P_A.PRSNL_ALIAS_TYPE_CD)
        , P_A.ROWID
        , P_A.UPDT_APPLCTX
        , P_A.UPDT_CNT
        , P_A.UPDT_DT_TM
        , P_A.UPDT_ID
        , P_A.UPDT_TASK

    FROM
        PRSNL_ALIAS   P_A

    WHERE P_A.PERSON_ID = 13215666

    WITH NOCOUNTER, SEPARATOR=" ", FORMAT
 */

 /* VALIDATER
    SELECT
        P_A.ACTIVE_IND
        , P_ACTIVE_STATUS_DISP = UAR_GET_CODE_DISPLAY(P_A.ACTIVE_STATUS_CD)
        , P_A.ACTIVE_STATUS_DT_TM
        , P_A.ACTIVE_STATUS_PRSNL_ID
        , P_A.ALIAS
        , P_ALIAS_POOL_DISP = UAR_GET_CODE_DISPLAY(P_A.ALIAS_POOL_CD)
        , P_A.BEG_EFFECTIVE_DT_TM
        , P_A.CHECK_DIGIT
        , P_CHECK_DIGIT_METHOD_DISP = UAR_GET_CODE_DISPLAY(P_A.CHECK_DIGIT_METHOD_CD)
        , P_CONTRIBUTOR_SYSTEM_DISP = UAR_GET_CODE_DISPLAY(P_A.CONTRIBUTOR_SYSTEM_CD)
        , P_DATA_STATUS_DISP = UAR_GET_CODE_DISPLAY(P_A.DATA_STATUS_CD)
        , P_A.DATA_STATUS_DT_TM
        , P_A.DATA_STATUS_PRSNL_ID
        , P_A.END_EFFECTIVE_DT_TM
        , P_A.PERSON_ID
        , P_A.PRSNL_ALIAS_ID
        , P_PRSNL_ALIAS_SUB_TYPE_DISP = UAR_GET_CODE_DISPLAY(P_A.PRSNL_ALIAS_SUB_TYPE_CD)
        , P_PRSNL_ALIAS_TYPE_DISP = UAR_GET_CODE_DISPLAY(P_A.PRSNL_ALIAS_TYPE_CD)
        , P_A.ROWID
        , P_A.UPDT_APPLCTX
        , P_A.UPDT_CNT
        , P_A.UPDT_DT_TM
        , P_A.UPDT_ID
        , P_A.UPDT_TASK

    FROM
        PRSNL_ALIAS   P_A

    WHERE 
        P_A.UPDT_ID = REQINFO->UPDT_ID
        AND
        P_A.UPDT_DT_TM > CNVTLOOKBEHIND("1,H")
        

    WITH NOCOUNTER, SEPARATOR=" ", FORMAT
  */