SELECT
	WEIGHT_RESULT_VAL = C.RESULT_VAL
	, 
    UPDATED = FORMAT(C.UPDT_DT_TM, "YYYY-MM-DD HH:MM:SS")
    ,
    PATIENT = P.NAME_FULL_FORMATTED
	, 
    *

FROM
	CLINICAL_EVENT      C
    ,
    PERSON              P

PLAN C

WHERE
	C.UPDT_DT_TM > CNVTLOOKBEHIND("35,D") ; ONLY GET'S DATA FROM OLDEST 35 DAYS AGO
	AND
	C.EVENT_CD = 7334438 ; FILTERS FOR "WEIGHT MEASURED"
	AND 
    C.VALID_UNTIL_DT_TM > SYSDATE ; STILL VALID (NOT INVALID)
	AND 
    C.PUBLISH_FLAG = 1 ; PUBLISH
	; AND 
    ; C.ENCNTR_ID = "XXXXXXXXXX" ; FOR A SPECIFIC PATIENT ENCOUNTER
    ; AND 
    ; C.PERSON_ID = 123456 ; For a specific patient
	
	
JOIN P
    WHERE
        P.PERSON_ID = C.PERSON_ID

ORDER BY
	C.UPDT_DT_TM    DESC

WITH MAXREC = 500, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10