SELECT
	PA.ALIAS

FROM
	PERSON   P
	, (LEFT JOIN PERSON_ALIAS PA ON (P.PERSON_ID = PA.PERSON_ID))

PLAN P
JOIN PA
WHERE 
	P.PERSON_ID = XXXXXXX ; Enter the person ID here
	AND
   	PA.ALIAS_POOL_CD = 9569589.00 ; this filters for the UR Number
	AND 
	PA.END_EFFECTIVE_DT_TM >CNVTDATETIME(CURDATE, curtime3)

WITH MAXREC = 10, NOCOUNTER, SEPARATOR=" ", FORMAT
