SELECT		
	UR_NUMBER = EA_URN.ALIAS	
	, PATIENT_NAME = P.NAME_FULL_FORMATTED  ;"XXXX"	
;	, PATIENT_ID = E_ORIG.PERSON_ID	
	, ENCNTR_DATES = CONCAT(FORMAT(E_ORIG.ARRIVE_DT_TM, "DD/MM/YY HH:MM"), " - ", FORMAT(E_ORIG.DEPART_DT_TM, "DD/MM/YY HH:MM"))	
		
	, VISIT_NO = EA_VISIT.ALIAS	
;	, E_ORIG.ENCNTR_ID	
	, UNIT = UAR_GET_CODE_DISPLAY(E_ORIG.LOC_NURSE_UNIT_CD)	
		
FROM		
	ENCOUNTER   E_ORIG	
	, (LEFT JOIN ENCNTR_ALIAS EA_URN ON EA_URN.ENCNTR_ID = E_ORIG.ENCNTR_ID	
	AND EA_URN.ENCNTR_ALIAS_TYPE_CD = 1079	; 'URN' FROM CODE SET 319
	AND EA_URN.ACTIVE_IND = 1	; ACTIVE URNS ONLY
	AND EA_URN.END_EFFECTIVE_DT_TM > SYSDATE	; EFFECTIVE URNS ONLY)
	)	
	, (LEFT JOIN ENCNTR_ALIAS EA_VISIT ON EA_VISIT.ENCNTR_ID = E_ORIG.ENCNTR_ID	
	AND EA_VISIT.ENCNTR_ALIAS_TYPE_CD = 1077	; 'FIN NBR' FROM CODE SET 319
	AND EA_VISIT.ACTIVE_IND = 1	; ACTIVE FIN NBRS ONLY
	AND EA_VISIT.END_EFFECTIVE_DT_TM > SYSDATE	; EFFECTIVE FIN NBRS ONLY)
	)	
	, (LEFT JOIN PERSON P ON P.PERSON_ID = E_ORIG.PERSON_ID)	
		
PLAN	E_ORIG	
	WHERE E_ORIG.LOC_NURSE_UNIT_CD = 116221126 ; RADU S2G	
JOIN	EA_URN	
JOIN	EA_VISIT	
JOIN	P	
		
ORDER BY		
	E_ORIG.DISCH_DT_TM	
		
WITH  TIME = 1200		
