drop program testing_query_88 go
create program testing_query_88

prompt
	"Output to File/Printer/MINE" = "MINE"   ;* Enter or select the printer or file name to send this report to.
	, "START TIME" = "SYSDATE"
	, "END TIME" = "SYSDATE"

with OUTDEV, STA_DATE_TM, END_DATE_TM
SELECT INTO $OUTDEV
	NURSE_UNIT = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
	, E.LOC_NURSE_UNIT_CD
	, DAYS = DATETIMEDIFF((CNVTDATETIME(CURDATE, curtime3)),E.ARRIVE_DT_TM,1)
	, E.ENCNTR_ID

FROM
	ENCOUNTER   E

WHERE
	E.ENCNTR_STATUS_CD = 854; active
	AND E.ACTIVE_IND = 1
	AND E.ARRIVE_DT_TM > CNVTDATETIME("01-JAN-2018 00:00:00.00")
	AND E.LOCATION_CD > 0
	AND E.LOC_NURSE_UNIT_CD > 0
	AND E.ENCNTR_TYPE_CD =      309308.00; INPATIENT
	AND E.PERSON_ID NOT IN
			(
	    	SELECT PERSON_FILTER.PERSON_ID
	        FROM PERSON PERSON_FILTER
	        WHERE PERSON_FILTER.NAME_LAST_KEY = "*TESTWHS*"
	        )
	;AND E.LOC_NURSE_UNIT_CD =       86167760.00; S3F
	AND (E.DISCH_DT_TM = NULL OR E.DISCH_DT_TM > CNVTDATETIME(CURDATE, curtime3))

ORDER BY E.LOC_NURSE_UNIT_CD


WITH SEPARATOR=" ", FORMAT, MAXCOL = 100

    end
    go