SELECT
	URN = PA.ALIAS
	, P.PERSON_ID
	, PATIENT = P.NAME_FULL_FORMATTED
	, E.ENCNTR_STATUS_CD
	, MED_SERVICE = UAR_GET_CODE_DISPLAY(E.MED_SERVICE_CD)
	, APPT_DATE = E.ARRIVE_DT_TM "DD/MM/YYYY HH:MM"
	, ORDERING_DR = PR.NAME_FULL_FORMATTED
	, ORDER_DATE = O.ORIG_ORDER_DT_TM
	, ORDERED_AS = O.ORDERED_AS_MNEMONIC
	, ORDER_DETAILS = O.ORDER_DETAIL_DISPLAY_LINE

    FROM
	ENCOUNTER       E
	, ORDERS        O
	, PERSON        P
	, PERSON_ALIAS  PA
	, PRSNL         PR

PLAN E
    WHERE
		E.ARRIVE_DT_TM BETWEEN ; FILTER FOR APPOINTMENTS IN THIS TIME RANGE
       		CNVTDATETIME("20-NOV-2022 00:00:00.00")
			AND
			CNVTDATETIME("30-NOV-2022 23:59:59.00")
        AND
        E.MED_SERVICE_CD IN (
			87625391.00;Orthopaedic Surgery
  			,86504090.00;Prosthetics & Orthoses
  			,98636040.00;SP Paed Orthopaedics
		)
        AND
        E.ACTIVE_IND = 1
