drop program wh_pbs_new_mappings go
create program wh_pbs_new_mappings

prompt
	"Output to File/Printer/MINE" = "MINE"   ;* Enter or select the printer or file name to send this report to.

with OUTDEV

SELECT INTO $OUTDEV		;RETRIEVES CODES THAT NEED TO BE MAPPED THIS MONTH.
    MAP_PBS_DRUG_ID_ = P_D.PBS_DRUG_ID
	; , DOMAIN = CURDOMAIN
	, PBS_CODE = P_L.PBS_ITEM_CODE
	; , PRIMARY_DRUG_NAME = P_I.DRUG_NAME
    , PBS_PRIMARY_DRUG_NAME_CORRECTED = REPLACE(P_I.DRUG_NAME," + ","-",0)
    , PBS_PRIMARY_DRUG_NAME = P_I.DRUG_NAME
    , MAPPED_PRIMARY = O_C_S_P.PRIMARY_NAME
	, BRAND_NAME = P_D.BRAND_NAME
    , TRADE_NAME_GENERATED = CONCAT
        (
            TRIM(P_D.BRAND_NAME)
            , " "
            , TRIM(REPLACE(P_D.FORM_STRENGTH, TRIM(P_I.DRUG_NAME), "", 0))
        )
	, GENERIC_NAME = P_D.FORM_STRENGTH
	, PRODUCT_PACKAGE_SIZE = P_D.PACK_SIZE
;	, PRODUCT_MANUFACTURER_CODE = P_M.MANUFACTURER_CODE
;	, SCHEDULE = P_L.DRUG_TYPE_MEAN
	, ITEM_BEG_DATE = FORMAT(P_I.BEG_EFFECTIVE_DT_TM, "DD/MMM/YYYY")
	, PRODUCT_BEG_DATE = FORMAT(P_D.BEG_EFFECTIVE_DT_TM, "DD/MMM/YYYY")

FROM
	 PBS_LISTING    P_L
	, PBS_ITEM      P_I
	, PBS_DRUG      P_D
    , (
		(SELECT
			PRIMARY_NAME = O.MNEMONIC
            SYNONYM_ID = O.SYNONYM_ID

		FROM
			ORDER_CATALOG_SYNONYM   O

		WHERE
            O.ACTIVE_IND = 1
            AND
            O.CATALOG_TYPE_CD = 2516; PHARMACY
            AND
            O.MNEMONIC_TYPE_CD IN
                (
                2583.00;	Primary
                )
		WITH SQLTYPE("VC200"))   O_C_S_P
	)

PLAN P_D
    WHERE	P_D.END_EFFECTIVE_DT_TM > (SYSDATE)	; CURRENT PRODUCTS ONLY
    ;ONLY SHOW CODES FROM THE MOST RECENT PACKAGE
    AND	P_D.BEG_EFFECTIVE_DT_TM = (SELECT MAX(BEG_EFFECTIVE_DT_TM) FROM PBS_DRUG)
    ;EXCLUDE BRAND ALTERATIONS
    AND	P_D.PBS_ITEM_ID NOT IN
    (
        SELECT P_D2.PBS_ITEM_ID FROM PBS_DRUG P_D2
        WHERE  P_D.PBS_ITEM_ID = P_D2.PBS_ITEM_ID
        AND P_D2.END_EFFECTIVE_DT_TM != CNVTDATETIME("31-DEC-2100")
    )

JOIN	P_I
    WHERE	P_I.PBS_ITEM_ID = P_D.PBS_ITEM_ID
    AND	P_I.END_EFFECTIVE_DT_TM > OUTERJOIN(SYSDATE)
    ;EXCLUDE ITEM ALTERATIONS
    AND	P_I.PBS_ITEM_ID NOT IN
        (
            SELECT P_I2.PBS_ITEM_ID FROM PBS_ITEM P_I2
            WHERE  P_I.PBS_ITEM_ID = P_I2.PBS_ITEM_ID
            AND P_I2.END_EFFECTIVE_DT_TM != CNVTDATETIME("31-DEC-2100")
        )

JOIN	P_L
    WHERE	P_L.PBS_LISTING_ID = P_I.PBS_LISTING_ID
    ; DON'T MAP THE PRIVATE HOSPITAL CODES ETC
    AND	P_L.DRUG_TYPE_MEAN NOT IN ("DB", "HS", "IN", "PQ", "TY")
    AND	P_L.PBS_ITEM_CODE IN
        (
            SELECT PBS_ITEM_CODE FROM PBS_PRESCRIBER
            WHERE PRESCRIBER_TYPE_CD IN
            (
                SELECT CV.CODE_VALUE FROM CODE_VALUE CV
                WHERE CV.CODE_SET = 4386008
                ;DON'T MAP DENTAL AND OPTOMETRIST CODES
                AND CV.CDF_MEANING IN ("M", "W", "N")
            )
            AND	END_EFFECTIVE_DT_TM = CNVTDATETIME("31-DEC-2100")
        )

JOIN P_O_M; PBS_OCS_MAPPING
    WHERE P_O_M.PBS_DRUG_ID = OUTERJOIN(P_D.PBS_DRUG)
        /* Get Mappings that are not expired at this time */
        P_O_M.END_EFFECTIVE_DT_TM > OUTERJOIN(SYSDATE)

JOIN O_C_S_P
    WHERE O_C_S_P.SYNONYM_ID = OUTERJOIN(P_O_M.SYNONYM_ID)
    AND
    O.ACTIVE_IND = 1
    AND
    O.CATALOG_TYPE_CD = 2516; PHARMACY
    AND
    O.MNEMONIC_TYPE_CD IN
        (
        2583.00;	Primary
        )

ORDER BY
	P_L.PBS_ITEM_CODE
	, P_I.DRUG_NAME
	, P_D.BRAND_NAME
	, P_D.FORM_STRENGTH

WITH TIME = 20,
	NOCOUNTER,
	SEPARATOR=" ",
	FORMAT


end
go
