drop program WH_Orthopedics_Rad_Orders go
create program WH_Orthopedics_Rad_Orders

prompt 
	"Output to File/Printer/MINE" = "MINE"           ;* Enter or select the printer or file name to send this report to.
	, "Start date for the Encounter" = "CURDATE"
	, "END date for the Encounter" = "CURDATE"
	, "Start Date for Order Filtering" = "CURDATE"
	, "End Date for Order Filtering" = "SYSDATE" 

with OUTDEV, START_DT_ENC, END_DT_ENC, START_DT_ORD, END_DT_ORD

SELECT into $OUTDEV

	PATIENT = P.NAME_FULL_FORMATTED
	, MED_SERVICE = UAR_GET_CODE_DISPLAY(ELH.MED_SERVICE_CD)
	, ENCOUNTER_DATE = ELH.BEG_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM"
	, ORDERING_DR = PR.NAME_FULL_FORMATTED
	, RADIOLOGY_ORDER_DATE = O.ORIG_ORDER_DT_TM
	, ORDER_NAME = O.ORDERED_AS_MNEMONIC
	, ORDER_DETAIL = O.ORDER_DETAIL_DISPLAY_LINE


FROM
	ENCNTR_LOC_HIST   ELH
	, ENCOUNTER   E
	, ORDERS   O
	, PERSON   P
	, PRSNL   PR
	; , SCH_APPT   S

PLAN ELH
	WHERE 
		ELH.MED_SERVICE_CD IN (
			87625391.00;Orthopaedic Surgery
  			,86504090.00;Prosthetics & Orthoses
  			,98636040.00;SP Paed Orthopaedics
		)
		AND
		ELH.BEG_EFFECTIVE_DT_TM BETWEEN ; FILTER FOR ORTHO APPOINTMENTS IN THIS TIME RANGE
       		CNVTDATETIME($START_DT_ENC)
			AND
			CNVTDATETIME($END_DT_ENC)

JOIN E ; ENCOUNTER
	WHERE 
		E.ENCNTR_ID = ELH.ENCNTR_ID
		AND
		E.ENCNTR_STATUS_CD IN (
			854.00 ;ACTIVE
			,856.00;DISCHARGED
			,666808.00; PENDING ARRIVAL
		)
		AND
		E.ENCNTR_TYPE_CD IN (309309.00); Outpatient Encounters only
		; AND
		; E.REG_DT_TM BETWEEN;> CNVTLOOKBEHIND("1,M")
        ; 	CNVTDATETIME("01-JAN-2022 00:00:00.00")
		; 	AND
		; 	CNVTDATETIME("31-JAN-2022 23:59:59.00")


; JOIN S ; SCH_APPT
; 	WHERE
; 		S.PERSON_ID = OUTERJOIN(E.PERSON_ID)
; 		AND

		; AND
		; S.beg_dt_tm BETWEEN
		; 	CNVTDATETIME("01-JUL-2022 00:00:00.00")
		; 	AND
		; 	CNVTDATETIME("31-JAN-2024 23:59:59.00")


JOIN P ; PERSON
	WHERE
		P.PERSON_ID = E.PERSON_ID
		AND
		P.ACTIVE_IND = 1
		

JOIN O ; ORDERS
	WHERE O.ENCNTR_ID = OUTERJOIN(ELH.ENCNTR_ID) ; OUTERJOIN => KEEP PATIENTS EVEN WITH NO RADIOLOGY ORDERS
	AND 
	O.CATALOG_TYPE_CD = OUTERJOIN(2517.00); RADIOLOGY Orders only; OUTERJOIN => KEEP PATIENTS EVEN WITH NO RADIOLOGY ORDERS
	AND
	O.ORIG_ORDER_DT_TM >= OUTERJOIN(CNVTDATETIME($START_DT_ORD)) ; Start date range of orders
	AND
	O.ORIG_ORDER_DT_TM <= OUTERJOIN(CNVTDATETIME($END_DT_ORD)) ; end date range of orders

JOIN PR ; PRSNL
	WHERE PR.PERSON_ID = OUTERJOIN(O.STATUS_PRSNL_ID)

ORDER BY
	ENCOUNTER_DATE   DESC	


WITH TIME = 20, SEPARATOR=" ", FORMAT


END
GO
