SELECT
	UPDATED = D.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, TIME_BEG = D.BEG_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, TIME_END = D.END_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, STAFF = PR.NAME_FULL_FORMATTED
	, PATIENT = PE.NAME_FULL_FORMATTED
	, PATIENT_ID = D.PERSON_ID
	, MED_SERVICE = uar_get_code_display(P.PCT_MED_SERVICE_CD)
	, P_PCT_TEAM_DISP = UAR_GET_CODE_DISPLAY(P.PCT_TEAM_CD)

FROM
	DCP_SHIFT_ASSIGNMENT   D
	, PCT_CARE_TEAM   P
	, PERSON   PE
	, PRSNL   PR

PLAN D
	WHERE
	D.PERSON_ID IN
		(
			SELECT E_A.ENCNTR_ID
			FROM ENCNTR_ALIAS E_A
			WHERE E_A.ALIAS = "30327008" ; EDIT THIS!
				AND E_A.ENCNTR_ALIAS_TYPE_CD = 1077	; 'FIN NBR' from code set 319
				AND E_A.ACTIVE_IND = 1	; active FIN NBRs only
				AND E_A.END_EFFECTIVE_DT_TM > SYSDATE	; effective FIN NBRs only
		)
	D.ENCNTR_ID IN
		(
			SELECT E_A.ENCNTR_ID
			FROM ENCNTR_ALIAS E_A
			WHERE E_A.ALIAS = "30327008" ; EDIT THIS!
				AND E_A.ENCNTR_ALIAS_TYPE_CD = 1077	; 'FIN NBR' from code set 319
				AND E_A.ACTIVE_IND = 1	; active FIN NBRs only
				AND E_A.END_EFFECTIVE_DT_TM > SYSDATE	; effective FIN NBRs only
		)

JOIN P WHERE P.PCT_CARE_TEAM_ID = D.PCT_CARE_TEAM_ID

JOIN PR WHERE PR.PERSON_ID = D.UPDT_ID

JOIN PE WHERE PE.PERSON_ID = D.PERSON_ID

WITH MAXREC = 1000, TIME = 20