SELECT			
	UPDATED = D.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"		
	, TIME_BEG = D.BEG_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"		
	, TIME_END = D.END_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"		
	, STAFF = PR.NAME_FULL_FORMATTED		
	, PATIENT = PE.NAME_FULL_FORMATTED		
	, PATIENT_ID = D.PERSON_ID
	, MED_SERVICE = uar_get_code_display(P.PCT_MED_SERVICE_CD)		
	, P_PCT_TEAM_DISP = UAR_GET_CODE_DISPLAY(P.PCT_TEAM_CD)		
			
FROM			
	DCP_SHIFT_ASSIGNMENT   D		
	, PCT_CARE_TEAM   P		
	, PERSON   PE		
	, PRSNL   PR		
			
PLAN D
/*			
	WHERE		
		'D.UPDT_ID = XXXX	
*/	
	
	WHERE		
		D.UPDT_DT_TM	
		BETWEEN	
			CNVTDATETIME("01-JUL-2022 00:00:00.00")
			AND
			CNVTDATETIME("12-JUL-2022 00:00:00.00")
		
JOIN P WHERE P.PCT_CARE_TEAM_ID = D.PCT_CARE_TEAM_ID			
	
JOIN PR WHERE PR.PERSON_ID = D.UPDT_ID			
			
JOIN PE WHERE PE.PERSON_ID = D.PERSON_ID			
			
WITH MAXREC = 1000, TIME = 20	