SELECT
	D.DESCRIPTION
	, D.NAME
	, D.OWNER_PRSNL_ID
	, D.PATIENT_LIST_ID
	, D_PATIENT_LIST_TYPE_DISP = UAR_GET_CODE_DISPLAY(D.PATIENT_LIST_TYPE_CD)
	, D.ROWID
	, D.UPDT_APPLCTX
	, D.UPDT_CNT
	, D.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, D.UPDT_ID
	, D.UPDT_TASK

FROM
	DCP_PATIENT_LIST   D

WHERE 
	;D.NAME = "*RADU*"
	;AND
	;D.PATIENT_LIST_TYPE_CD IN (SELECT CODE_VALUE FROM CODE_VALUE WHERE DISPLAY_KEY = "*SERVICE*")
	;AND
	D.UPDT_DT_TM > CNVTDATETIME("10-JUL-2022 00:00:00.00")
	AND
	D.UPDT_ID = xxx ; VAR

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10