SELECT DISTINCT
	 FACILITY = UAR_GET_CODE_DISPLAY(E.LOC_FACILITY_CD)
	, NURSE_UNIT = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
	, LOCATION = UAR_GET_CODE_DISPLAY(E.LOCATION_CD)
	, ROOM = UAR_GET_CODE_DISPLAY(E.LOC_ROOM_CD)
	, BED = UAR_GET_CODE_DISPLAY(E.LOC_BED_CD)
	, PATIENT_URN = P_A.ALIAS
	, PATIENT_NAME = P.NAME_FULL_FORMATTED
	, GENDER = UAR_GET_CODE_DISPLAY(P.SEX_CD)
	, ENCOUNTER_ID = E.ENCNTR_ID
	, DIAGNOSIS = D.DIAGNOSIS_DISPLAY
	, DIAGNOSIS_TYPE = UAR_GET_CODE_DISPLAY(D.DIAG_TYPE_CD)
	, MED_SERVICE = UAR_GET_CODE_DISPLAY(E.MED_SERVICE_CD)
	, ARRIVE_TIME = E.ARRIVE_DT_TM
	, E.BEG_EFFECTIVE_DT_TM
FROM
	ENCOUNTER   E
	, DIAGNOSIS   D
	, PERSON_ALIAS   P_A
	, PERSON   P
    /* Table with test patients id's */
    ,
    (
		(SELECT TEST_PATIENT_IDS = X.PERSON_ID
		FROM PERSON   X
		WHERE X.NAME_LAST_KEY = "TESTWHS"
		WITH SQLTYPE("F8"))   IN_TP
	)

PLAN D
	WHERE
	CNVTUPPER(D.DIAGNOSIS_DISPLAY) = PATSTRING("*ALZHEIMER*")
    AND D.PERSON_ID NOT IN (TEST_PATIENT_IDS.IN_TP)
JOIN E;ENCOUNTER
    WHERE D.PERSON_ID = E.PERSON_ID
    /* Not "DEMO 1 HOSPITAL" Removes Fake Data From The Demo Hospital */
    AND E.LOC_FACILITY_CD != 4038465.00
    /* Remove Fake 'Test' Patients */
	AND E.ARRIVE_DT_TM >= CNVTDATETIME("01-OCT-2021 00:00:00.00")
JOIN P_A
	WHERE P_A.PERSON_ID = E.PERSON_ID
	AND	P_A.ALIAS_POOL_CD = 9569589 ; URN ALIAS ONLY
	AND	P_A.ACTIVE_IND = 1
JOIN P
	WHERE P.PERSON_ID = E.PERSON_ID
	AND P.ACTIVE_IND = 1
    AND P.NAME_LAST_KEY != "TESTWHS"
ORDER BY
	PATIENT_URN   DESC
	, 0
WITH MAXREC = 1000000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10