SELECT
    NO_SCAN_REASON = UAR_GET_CODE_DISPLAY(MAPE.REASON_CD)
	, DT_COMPLETED = MAPE.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, DT_COMPLETED_YEAR = MAPE.UPDT_DT_TM "YYYY;;D"
	, DT_COMPLETED_MONTH = MAPE.UPDT_DT_TM "MM;;D"
	, DT_COMPLETED_DAY = MAPE.UPDT_DT_TM "DD;;D"
	, DT_COMPLETED_TIME = MAPE.UPDT_DT_TM "HH:MM:SS;;D"
	, SOURCE_APP = EVALUATE(
		MAE.SOURCE_APPLICATION_FLAG
		, 0, "Default - no value"
		, 1, "Care Mobil"
		, 2, "MAW (Care Admin in DB)"
		, 3, "MAR (PowerChart in DB)"
		)
	, ORDERED = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, STAFF = PR.NAME_FULL_FORMATTED
	, E_LOC_NURSE_UNIT_DISP = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
    , E_MED_SERVICE_DISP = UAR_GET_CODE_DISPLAY(E.MED_SERVICE_CD)
    , SCANNED = MAE.POSITIVE_PATIENT_IDENT_IND
    , MAA_MED_ADMIN_ALERT_ID = MAA.MED_ADMIN_ALERT_ID
    , MAPE_MED_ADMIN_ALERT_ID = MAPE.MED_ADMIN_ALERT_ID
    , PR_PERSON_ID = PR.PERSON_ID
    , MAE_PRSNL_ID = MAE.PRSNL_ID
    , MAE_MED_ADMIN_EVENT_ID = MAE.MED_ADMIN_EVENT_ID
    , MAA_MED_ADMIN_EVENT_ID = MAA.MED_ADMIN_EVENT_ID
    , CE_EVENT_ID = CE.EVENT_ID
    , MAE_EVENT_ID = MAE.EVENT_ID
    , P_PERSON_ID = P.PERSON_ID
    , CE_PERSON_ID = CE.PERSON_ID
    , E_ENCNTR_ID = E.ENCNTR_ID
    , CE_ENCNTR_ID = CE.ENCNTR_ID

FROM
    MED_ADMIN_PT_ERROR  MAPE
    , MED_ADMIN_ALERT   MAA
    , PRSNL             PR
    , MED_ADMIN_EVENT   MAE
    , CLINICAL_EVENT    CE
    , PERSON            P
    , ENCOUNTER         E
    , ORDERS            O                 

PLAN MAPE
    WHERE MAPE.UPDT_DT_TM > CNVTLOOKBEHIND("1,D")

JOIN MAA    WHERE   MAA.MED_ADMIN_ALERT_ID      = OUTERJOIN(MAPE.MED_ADMIN_ALERT_ID)
JOIN PR     WHERE   PR.PRSNL                    = OUTERJOIN(MAE.PRSNL_ID)
JOIN MAE    WHERE   MAE.MED_ADMIN_EVENT_ID      = OUTERJOIN(MAA.MED_ADMIN_EVENT_ID)
JOIN CE     WHERE   CE.EVENT_ID                 = OUTERJOIN(MAE.EVENT_ID)
JOIN P      WHERE   P.PERSON_ID                 = OUTERJOIN(CE.PERSON_ID)
JOIN E      WHERE   E.ENCNTR_ID                 = OUTERJOIN(CE.ENCNTR_ID)
JOIN O      WHERE   O.ORDER_ID                  = OUTERJOIN(CE.ORDER_ID)

WITH MAXREC = 2000, TIME=10