SELETCT
	, SCANNED = MAE.POSITIVE_PATIENT_IDENT_IND
	, NO_SCAN_REASON = UAR_GET_CODE_DISPLAY(MAPE.REASON_CD)

FROM
;	ORDERS   O
;	, PERSON   P
;	, PERSON_ALIAS	PA
;	, PRSNL   PR
;	, MED_ADMIN_EVENT   MAE
;	, ENCOUNTER   E
;	, MED_ADMIN_MED_ERROR   MAME
	, MED_ADMIN_ALERT   MAA
	, MED_ADMIN_PT_ERROR   MAPE

PLAN

JOIN

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10