SELECT
	MAPE.BAR_CODE_IDENT
	, MAPE.EXPECTED_PT_ID
	, MAPE.FREETEXT_REASON
	, MAPE.IDENTIFIED_PT_ID
	, MAPE.MED_ADMIN_ALERT_ID
	, MAPE.MED_ADMIN_PT_ERROR_ID
	, MAPE_REASON_DISP = UAR_GET_CODE_DISPLAY(MAPE.REASON_CD)
	, MAPE.ROWID
	, MAPE.UPDT_APPLCTX
	, MAPE.UPDT_CNT
	, MAPE.UPDT_DT_TM
	, MAPE.UPDT_ID
	, MAPE.UPDT_TASK

FROM
	MED_ADMIN_PT_ERROR   MAPE

WHERE 
	MAPE.UPDT_DT_TM
	BETWEEN
	CNVTDATETIME("01-JUL-2022 00:00:00.00")
	AND
	CNVTDATETIME("01-SEP-2022 00:00:00.00")

WITH NOCOUNTER, SEPARATOR=" ", FORMAT
