SELECT
	D.PATIENT_LIST_ID
	, D.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, STAFF_UPDATER = P.NAME_FULL_FORMATTED
	, PATIENT = PE.NAME_FULL_FORMATTED
	, LIST_NAME = DP.NAME

FROM
	DCP_PL_CUSTOM_ENTRY   D
	, PRSNL   P
	, PERSON   PE
	, DCP_PATIENT_LIST   DP

PLAN D
	WHERE 
		;D.UPDT_ID = xxxx
		D.UPDT_DT_TM BETWEEN
			CNVTDATETIME("10-JUL-2021 00:00:00.00")
			AND
			CNVTDATETIME("11-JUL-2021 00:00:00.00")
JOIN P
	WHERE P.PERSON_ID = D.UPDT_ID
JOIN PE
	WHERE PE.PERSON_ID = D.PERSON_ID
JOIN DP
	WHERE DP.PATIENT_LIST_ID = D.PATIENT_LIST_ID

WITH MAXREC = 50000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10