SELECT
	D.BEG_EFFECTIVE_DT_TM
	, D.END_EFFECTIVE_DT_TM
	, D_ASSIGNMENT_GROUP_DISP = UAR_GET_CODE_DISPLAY(D.ASSIGNMENT_GROUP_CD)
	, D_ASSIGNMENT_POS_DISP = UAR_GET_CODE_DISPLAY(D.ASSIGNMENT_POS_CD)
	, D_ASSIGN_TYPE_DISP = UAR_GET_CODE_DISPLAY(D.ASSIGN_TYPE_CD)
	, D_LOC_BED_DISP = UAR_GET_CODE_DISPLAY(D.LOC_BED_CD)
	, D_LOC_BUILDING_DISP = UAR_GET_CODE_DISPLAY(D.LOC_BUILDING_CD)
	, D_LOC_FACILITY_DISP = UAR_GET_CODE_DISPLAY(D.LOC_FACILITY_CD)
	, D_LOC_ROOM_DISP = UAR_GET_CODE_DISPLAY(D.LOC_ROOM_CD)
	, D_LOC_UNIT_DISP = UAR_GET_CODE_DISPLAY(D.LOC_UNIT_CD)
	, P_PCT_MED_SERVICE_DISP = UAR_GET_CODE_DISPLAY(P.PCT_MED_SERVICE_CD)
	, P_PCT_ROLE_DISP = UAR_GET_CODE_DISPLAY(P.PCT_ROLE_CD)
	, P_PCT_TEAM_DISP = UAR_GET_CODE_DISPLAY(P.PCT_TEAM_CD)
	, URN = PA.ALIAS
	, STAFF_UPDATER = PR.NAME_FULL_FORMATTED

FROM
	DCP_SHIFT_ASSIGNMENT   D
	, PCT_CARE_TEAM   P
	, PRSNL   PR
	, PERSON   PE
	, PERSON_ALIAS   PA

PLAN D ; DCP_SHIFT_ASSIGNMENT
	WHERE  D.UPDT_DT_TM > CNVTDATETIME("10-JAN-2000 00:00:00.00")

JOIN P ; PCT_CARE_TEAM
	WHERE P.PCT_CARE_TEAM_ID = D.PCT_CARE_TEAM_ID

JOIN PR
	WHERE PR.PERSON_ID = D.UPDT_ID

JOIN PE
	WHERE PE.PERSON_ID = D.PERSON_ID

JOIN PA
	WHERE PA.PERSON_ID = D.PERSON_ID
	AND PA.ACTIVE_IND = 1
	AND PA.PERSON_ALIAS_TYPE_CD = 10; URN

WITH MAXREC = 1000000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 60
