SELECT
	C_V.DISPLAY
	, C_V.DESCRIPTION
	, C_V.DISPLAY_KEY
	, C_V.ACTIVE_IND
	, C_V.BEGIN_EFFECTIVE_DT_TM "DD-MMM-YYYY HH:MM:SS;;D"
	, C_V.END_EFFECTIVE_DT_TM "DD-MMM-YYYY HH:MM:SS;;D"
	, ALIAS_OUTBOUND_SOURCE = UAR_GET_CODE_DISPLAY(C_V_O.CONTRIBUTOR_SOURCE_CD)
	, ALIAS_OUTBOUND = C_V_O.ALIAS
	, C_V_DATA_STATUS_DISP = UAR_GET_CODE_DISPLAY(C_V.DATA_STATUS_CD)
	, C_V.UPDT_DT_TM "DD-MMM-YYYY HH:MM:SS;;D"
	, C_V.CODE_VALUE

FROM
	CODE_VALUE   				C_V
	, CODE_VALUE_OUTBOUND		C_V_O

PLAN C_V ;CODE_VALUE
	WHERE C_V.CODE_SET = 34 ; 'HOSP_SERV' aka on the front end in Powerchart as Clinical Unit

JOIN C_V_O
	WHERE C_V_O.CODE_VALUE = OUTERJOIN(C_V.CODE_VALUE)

ORDER BY
C_V.ACTIVE_IND DESC
, C_V.DISPLAY


WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME= 15
