UPDATE INTO PRSNL P
SET 
    P.PHYSICIAN_IND = 1
    , P.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , P.UPDT_ID = REQINFO->UPDT_ID
    , P.UPDT_CNT = CRED.UPDT_CNT + 1
WHERE 
    P.POSITION_CD = 9655109 ; 9655109 IS MEDICAL OFFICER P1 IN P2031
    AND 
    P.PHYSICIAN_IND = 0 ; Where the physician ind is zero