with OUTDEV
DECLARE DEPT_DISP_NAME_VAR = VC WITH PROTECT
 
;insert update scripts here

/*
****IN DEVELOPMENT********
*/


; UPDATE SCRIPT START FOR swapme123
SELECT INTO "NL:"
    NAME = O_C.DEPT_DISPLAY_NAME
FROM
    ORDER_CATALOG O_C
WHERE
    O_C.CATALOG_CD = swapme123
HEAD
    DEPT_DISP_NAME_VAR = REPLACE (NAME, "  ", " ")
UPDATE INTO ORDER_CATALOG O_C
SET
    O_C.DEPT_DISPLAY_NAME = DEPT_DISP_NAME_VAR
    , O_C.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , O_C.UPDT_ID = REQINFO->UPDT_ID
    , O_C.UPDT_CNT = O_C.UPDT_CNT + 1
WHERE
    O_C.CATALOG_CD = swapme123
; UPDATE SCRIPT END FOR swapme123



/*
; QUERY
SELECT
	O.DEPT_DISPLAY_NAME
	, O.CATALOG_CD

FROM
	ORDER_CATALOG   O

WHERE O.DEPT_DISPLAY_NAME = "*  *"

WITH MAXREC = 1000000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 100
 */