/*

****IN DEVELOPMENT********
*/


UPDATE INTO PERSON P
SET
    P.END_EFFECTIVE_DT_TM = CNVTDATETIME("31-DEC-2100")
    , P.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , P.UPDT_ID = REQINFO->UPDT_ID
    , P.UPDT_CNT = P.UPDT_CNT + 1
WHERE
    P.END_EFFECTIVE_DT_TM > CNVTDATETIME("31-DEC-2100 23:59:59.00")

END
GO