/*
****IN DEVELOPMENT********
*/

UPDATE INTO ORDER_CATALOG O_C
SET
    O_C.DEPT_DISPLAY_NAME = O_C.DEPT_DISPLAY_NAME
    , O_C.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , O_C.UPDT_ID = REQINFO->UPDT_ID
    , O_C.UPDT_CNT = O_C.UPDT_CNT + 1
WHERE
    O_C.CATALOG_CD = SWAPME123

/*
; QUERY
SELECT
	O.DEPT_DISPLAY_NAME
	, O.CATALOG_CD

FROM
	ORDER_CATALOG   O

WHERE O.DEPT_DISPLAY_NAME = "*  *"

WITH MAXREC = 1000000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 100
 */