; HIDE FLAG UPDATE SCRIPT---------------------------------------------------------
UPDATE INTO
    ORDER_CATALOG_SYNONYM   O_C_S
SET
    O_C_S.HIDE_FLAG = 0 ; MAKE VIEWABLE
    ; TRACKING UPDATES BELOW
    , O_C_S.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , O_C_S.UPDT_ID = REQINFO->UPDT_ID
    , O_C_S.UPDT_CNT = O_C_S.UPDT_CNT + 1
WHERE
    O_C_S.HIDE_FLAG = 1 ; IS CURRENTLY HIDDEN
    AND O_C_S.SYNONYM_ID = _SYNONYM_ID_ ;EDIT THIS WITH ACTUAL ID

; END OF UPDATE SCRIPT ------------------------------------------------------------






; QUERY --------------------------------------------------------------------------------------------------------
SELECT
    _SYNONYM_ID_ = O_C_S.SYNONYM_ID
    , HIDE_FLAG = O_C_S.HIDE_FLAG
	, O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O_C_S.CATALOG_CD)
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O_C_S.CATALOG_TYPE_CD)
    , O_C_S_MNEMONIC_TYPE_DISP = UAR_GET_CODE_DISPLAY(O_C_S.MNEMONIC_TYPE_CD)
    , O_C_S.MNEMONIC_KEY_CAP
    , O_C_S.MNEMONIC
	, UPDATED = FORMAT(O_C_S.UPDT_DT_TM,"DD/MMM/YYYY HH:MM;3;Q")
	, UPDATER = PR.NAME_FULL_FORMATTED

FROM
	ORDER_CATALOG_SYNONYM   O_C_S
	, PRSNL                 PR

PLAN O_C_S ; ORDER_CATALOG_SYNONYM
	WHERE
        O_C_S.HIDE_FLAG = 1 ; ONLY STUFF THAT IS HIDDEN
        AND O_C_S.UPDT_ID = REQINFO->UPDT_ID ; UPDATER IS CURRENT USER ONLY
        AND O_C_S.UPDT_DT_TM > cnvtlookbehind("5, D") ; EDITED IN THE LAST X DAYS
		AND O_C_S.CATALOG_TYPE_CD = 2513.00 ; ONLY THIS CATALOG TYPE
            /*
            2516.00	Pharmacy
            2517.00	Radiology
            2513.00	Laboratory
            */
		AND O_C_S.MNEMONIC_KEY_CAP = "*MPOX*" ; WILD CARD SEARCH

JOIN PR ; PRSNL
	WHERE
		PR.PERSON_ID = O_C_S.UPDT_ID

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10
