

;---OEF default field value correction---------------------------------------------------------------------------------
UPDATE INTO
    OE_FORMAT_FIELDS    OEF_FIELDS
SET
    OEF_FIELDS.DEFAULT_VALUE = "__DEFAULT_VALUE__" ; EDIT THIS!
    , OEF_FIELDS.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , OEF_FIELDS.UPDT_ID = REQINFO->UPDT_ID
    , OEF_FIELDS.UPDT_CNT = OEF_FIELDS.UPDT_CNT + 1
WHERE
    OEF_FIELDS.OE_FORMAT_ID = __OE_FORMAT_ID__ ; EDIT THIS! F8
    AND OEF_FIELDS.ACTION_TYPE_CD = __ACTION_TYPE_CD__ ; EDIT THIS! F8
    AND OEF_FIELDS.OE_FIELD_ID = __OE_FIELD_ID__ ; EDIT THIS! F8
;----------------------------------------------------------------------------------------------------------------------

;QUERY FOR SCRIPT
SELECT
	__OE_FORMAT_ID__ = OEF.OE_FORMAT_ID
	, OEF_NAME = OEF.OE_FORMAT_NAME
	, __OE_FIELD_ID__ = OEF_FIELDS.OE_FIELD_ID
	, OEF_FIELDS.LABEL_TEXT
	, __ACTION_TYPE_CD__ = OEF_FIELDS.ACTION_TYPE_CD
    , FIELD_ID_RANK = RANK() OVER(PARTITION BY OEF.OE_FORMAT_NAME ORDER BY OEF_FIELDS.OE_FIELD_ID)
    , OEF_FIELDS.GROUP_SEQ
    , __DEFAULT_VALUE__ = '=TEXTJOIN(",", TRUE, IF($A$1:$A$10000=INDEX($A:$A, ROW()), $F$1:$F$10000, ""))'
	, LENGTH  = '=LEN(INDIRECT("H" & ROW()))'
	, CURRENT_DEFAULT_VALUE = OEF_FIELDS.DEFAULT_VALUE
	, CURRENT_DEFAULT_VALUE_LENGTH = '=LEN(INDIRECT("J" & ROW()))'

FROM
	ORDER_ENTRY_FORMAT   OEF
	, OE_FORMAT_FIELDS   OEF_FIELDS

PLAN
    OEF ; ORDER_ENTRY_FORMAT
    WHERE OEF.CATALOG_TYPE_CD = 2517 ; Radiology
    AND oef.action_type_cd =        2534.00; Order

JOIN
    OEF_FIELDS ;OE_FORMAT_FIELDS
    WHERE OEF_FIELDS.OE_FORMAT_ID = OEF.OE_FORMAT_ID
    AND OEF_FIELDS.ACTION_TYPE_CD = 2534.00; Order
    AND OEF_FIELDS.LABEL_TEXT != "Outpatient Paper Order"
	AND OEF_FIELDS.LABEL_TEXT != "Request Date/Time"

ORDER BY
	OEF.OE_FORMAT_NAME
	, OEF_FIELDS.GROUP_SEQ
	, OEF_FIELDS.FIELD_SEQ
	, OEF_FIELDS.ROWID   DESC

WITH TIME = 30