; THIS WILL DELETE AN OEF FIELD FROM A FORM ---------------
DELETE FROM
    OE_FORMAT_FIELDS    OEF_FIELDS
WHERE
    OEF_FIELDS.OE_FORMAT_ID = _OE_FORMAT_ID_ ;REPLACE
    AND OEF_FIELDS.ACTION_TYPE_CD = _ACTION_TYPE_CD_ ; REPLACE
    AND OEF_FIELDS.OE_FIELD_ID = _OE_FIELD_ID_ ;REPLACE
    AND OEF_FIELDS.LABEL_TEXT = _LABEL_TEXT_ ;REPLACE
;----------------------------------------------------------

/*
THE CODE BELOW WILL RETRIEVE THE VALUES YOU NEED FOR THE "REPLACE LINES ABOVE"
*/
SELECT DISTINCT
	_OE_FORMAT_ID_ = OEF.OE_FORMAT_ID
	, OEF_NAME = OEF.OE_FORMAT_NAME
	, _OE_FIELD_ID_ = OEF_FIELDS.OE_FIELD_ID
	, _LABEL_TEXT_ = OEF_FIELDS.LABEL_TEXT
	, _ACTION_TYPE_CD_ = OEF_FIELDS.ACTION_TYPE_CD
    , FIELD_ID_RANK = RANK() OVER(PARTITION BY OEF.OE_FORMAT_NAME ORDER BY OEF_FIELDS.OE_FIELD_ID)
    , OEF_FIELDS.GROUP_SEQ
    , FIELD_SEQUENCE = '=TEXTJOIN(",", TRUE, IF($A$1:$A$10000=INDEX($A:$A, ROW()), $F$1:$F$10000, ""))'
	, FIELD_SEQUENCE_LENGTH  = '=LEN(INDIRECT("H" & ROW()))'
FROM
	ORDER_ENTRY_FORMAT   OEF
	, OE_FORMAT_FIELDS   OEF_FIELDS
PLAN
    OEF ; ORDER_ENTRY_FORMAT
    WHERE OEF.CATALOG_TYPE_CD = 2517 ; Radiology ; CAN EDIT
    AND oef.action_type_cd =        2534.00; Order ; CAN EDIT
JOIN
    OEF_FIELDS ;OE_FORMAT_FIELDS
    WHERE OEF_FIELDS.OE_FORMAT_ID = OEF.OE_FORMAT_ID
    AND OEF_FIELDS.ACTION_TYPE_CD = 2534.00; Order ; CAN EDIT
    AND OEF_FIELDS.LABEL_TEXT != "Outpatient Paper Order" ; CAN EDIT
	AND OEF_FIELDS.LABEL_TEXT != "Request Date/Time"; CAN EDIT
ORDER BY
	OEF.OE_FORMAT_NAME
	, OEF_FIELDS.GROUP_SEQ
	, OEF_FIELDS.FIELD_SEQ
	, OEF_FIELDS.ROWID   DESC
WITH TIME = 10
