SELECT
    P.USERNAME
    , P.NAME_FULL_FORMATTED
	, C_CREDENTIAL_DISP = UAR_GET_CODE_DISPLAY(C.CREDENTIAL_CD)
	, C.END_EFFECTIVE_DT_TM

FROM
	CREDENTIAL   C
	, (LEFT JOIN PRSNL P ON (C.PRSNL_ID = P.PERSON_ID))

PLAN C
    WHERE
	    C.CREDENTIAL_CD IN(78912321)
		/*
		78912321	SMO		Senior / Consultant-Medical Officer
        */

JOIN
    P
        WHERE
	    P.END_EFFECTIVE_DT_TM > SYSDATE
	    AND
	    P.ACTIVE_IND = 1

WITH MAXREC = 50000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 30