SELECT
/*
This query extracts all the current oncology patients and displays their medications to be administered
 */
	PATIENT = E.NAME_FULL_FORMATTED
	,
    P_ID = E.PERSON_ID
	,
    ADMIT = NULLVAL(E.ARRIVE_DT_TM,E.REG_DT_TM) "@SHORTDATETIME"
	,
    DEPART = NULLVAL(E.DEPART_DT_TM,E.DISCH_DT_TM) "@SHORTDATETIME"
	,
    ENCNTR_DATES = CONCAT(
  		IF (NULLIND(E.ARRIVE_DT_TM)=1) FORMAT(E.REG_DT_TM,"DD/MM/YY HH:MM")
  		ELSE FORMAT(E.ARRIVE_DT_TM,"DD/MM/YY HH:MM") 
        ENDIF
  		," - ",
  		IF(NULLIND(E.DEPART_DT_TM)=1) FORMAT(E.DISCH_DT_TM,"DD/MM/YY HH:MM")
  		ELSE FORMAT(E.DEPART_DT_TM,"DD/MM/YY HH:MM") 
        ENDIF
  		)
    ,
    SCHEDULTED_TIME = TA.SCHEDULED_DT_TM "DD/MM/YYYY HH:MM"
    , 
    DOSAGE_UNIT = UAR_GET_CODE_DISPLAY( CEM.DOSAGE_UNIT_CD )
	, 
    ROUTE = UAR_GET_CODE_DISPLAY( CEM.ADMIN_ROUTE_CD )
	, 
    FREQUENCY = UAR_GET_CODE_DISPLAY( FS.FREQUENCY_CD )
	, 
    O.SIMPLIFIED_DISPLAY_LINE
	, 
    NURSE = PR.NAME_FULL_FORMATTED

FROM
    CLINICAL_EVENT		CE
	, 
	ENCOUNTER           E
    ,
    TASK_ACTIVITY       TA
    ,
    ORDERS              O
    ,
    CE_MED_RESULT		CEM
	, 
    TASK_ACTIVITY		TA
	, 
    ENCNTR_ALIAS		EA
	, 
    PERSON			    P
	, 
    PRSNL				PR
	, 
    ORDERS			    O
	, 
    FREQUENCY_SCHEDULE	FS

PLAN CE
    WHERE
        ; CE.PERFORMED_DT_TM
        ;     BETWEEN
        ;         CNVTDATETIME( CNVTDATE( 090122 ), 0000 )
        ;         AND
        ;         CNVTDATETIME( CNVTDATE( 090122 ), 2359 )
	    ; AND 
        CE.RESULT_STATUS_CD = 601	; AUTH VERIFIED
	    AND CE.EVENT_CLASS_CD = 529		; MED
	    AND CE.EVENT_RELTN_CD = 580		; CHILD

JOIN E;ENCOUNTER
    WHERE E.ENCNTR_ID = CE.ENCNTR_ID
        E.MED_SERVICE_CD = 313015 ; 'ONCOLOGY' MED SERVICE PATIENTS
        AND (;DEPARTED DATE IS IN THE FUTURE OR NEVER AT ALL
            E.DEPART_DT_TM > CNVTDATETIME(CURDATE, CURTIME3)
            OR
            E.DISCH_DT_TM > CNVTDATETIME(CURDATE, CURTIME3)
            OR 
            (E.DEPART_DT_TM IS NULL AND E.DISCH_DT_TM IS NULL)
        )
        AND (; RECORDED DATE IS TURNED UP IN THE PAST
            E.ARRIVE_DT_TM < CNVTDATETIME(CURDATE, CURTIME3)
            OR
            E.REG_DT_TM < CNVTDATETIME(CURDATE, CURTIME3)
        )
        AND E.ACTIVE_IND = 1 ; ENCOUNTER IS ACTIVE

JOIN TA ;TASK_ACTIVITY
    WHERE	TA.ORDER_ID = CE.ORDER_ID
		AND TA.CATALOG_TYPE_CD = VALUE( UAR_GET_CODE_BY( "MEANING", 6000, "PHARMACY" ) )
		AND TA.TASK_TYPE_CD = VALUE( UAR_GET_CODE_BY( "MEANING", 6026, "MED" ) ) 
		AND TA.SCHEDULED_DT_TM != NULL
		AND TA.ACTIVE_IND = 1

JOIN O
    WHERE O.ORDER_ID = CE.ORDER_ID
        AND
    	O.ORIG_ORDER_DT_TM BETWEEN 
		    CNVTDATETIME("05-DEC-2021 00:00:00.00")
		    AND
		    CNVTDATETIME("06-DEC-2021 00:00:00.00")
		AND 
        O.ACTIVE_IND = 1



