SELECT
	O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, pharmacy_cd = O.CATALOG_CD
	, O.ENCNTR_ID
	, O.ORDER_ID
	, O.ORIG_ORDER_DT_TM
	, O.PERSON_ID
	, P.NAME_FULL_FORMATTED
	, E_LOC_BUILDING_DISP = UAR_GET_CODE_DISPLAY(E.LOC_BUILDING_CD)
	, E_LOC_NURSE_UNIT_DISP = UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
	, E_ENCNTR_TYPE_DISP = UAR_GET_CODE_DISPLAY(E.ENCNTR_TYPE_CD)
	, E.INPATIENT_ADMIT_DT_TM
	; Clinical Unit

FROM
	ORDERS   O
	, (LEFT JOIN PERSON P ON (P.PERSON_ID = O.PERSON_ID))
	, (INNER JOIN ENCOUNTER E ON (E.ENCNTR_ID = O.ENCNTR_ID))

PLAN 
	O 
	WHERE
		(O.ORIG_ORDER_DT_TM BETWEEN 
			CNVTDATETIME("01-FEB-2021 00:00:00.00")
			AND
			CNVTDATETIME("02-FEB-2021 00:00:00.00")
			; CNVTDATETIME("01-AUG-2021 23:59:59.00")
		) ; Date range filter above
		AND
		O.CATALOG_TYPE_CD = 2516 ; Filters for only 'Pharmacy'
		AND
		O.ORDER_STATUS_CD = 2543 ; Filters for only 'Completed' order status'

JOIN P 
    WHERE P.PERSON_ID = O.PERSON_ID

JOIN E WHERE E.ENCNTR_ID = O.ENCNTR_ID
	AND (
		E.ENCNTR_TYPE_CD = 309308 ; Only inpatient encounters
		AND(
		E.LOC_BUILDING_CD = 86164609 ; Sunshine Location
		OR
		E.LOC_BUILDING_CD = 85758827 ; Footscray Location
		)
	)

ORDER BY
	O.PERSON_ID
	, O.ENCNTR_ID

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 600




















SELECT
/*
This query extracts all the current oncology patients
 */
	E.NAME_FULL_FORMATTED
	, E.PERSON_ID
	, ADMIT = NULLVAL(E.ARRIVE_DT_TM,E.REG_DT_TM) "@SHORTDATETIME"
	, DEPART = NULLVAL(E.DEPART_DT_TM,E.DISCH_DT_TM) "@SHORTDATETIME"
	, ENCNTR_DATES = CONCAT(
  		IF (NULLIND(E.ARRIVE_DT_TM)=1) FORMAT(E.REG_DT_TM,"DD/MM/YY HH:MM")
  		ELSE FORMAT(E.ARRIVE_DT_TM,"DD/MM/YY HH:MM") ENDIF
  		," - ",
  		IF(NULLIND(E.DEPART_DT_TM)=1) FORMAT(E.DISCH_DT_TM,"DD/MM/YY HH:MM")
  		ELSE FORMAT(E.DEPART_DT_TM,"DD/MM/YY HH:MM") ENDIF
  		)

FROM
	ENCOUNTER   E

WHERE  
	E.MED_SERVICE_CD = 313015 ; 'ONCOLOGY' MED SERVICE PATIENTS
	AND (;DEPARTED DATE IS IN THE FUTURE OR NEVER AT ALL
		E.DEPART_DT_TM > CNVTDATETIME(CURDATE, CURTIME3)
		OR
		E.DISCH_DT_TM > CNVTDATETIME(CURDATE, CURTIME3)
		OR 
        (E.DEPART_DT_TM IS NULL AND E.DISCH_DT_TM IS NULL)
    )
	AND (; RECORDED DATE IS TURNED UP IN THE PAST
        E.ARRIVE_DT_TM < CNVTDATETIME(CURDATE, CURTIME3)
        OR 
        E.REG_DT_TM < CNVTDATETIME(CURDATE, CURTIME3)
    )

WITH MAXROW = 5000, NOCOUNTER, SEPARATOR=" ", FORMAT
