SELECT
/*
This query extracts all the current oncology patients and displays their medications to be administered
 */
	CE.EVENT_CD
    ,
    EVENT_CODE_DISPLAY = UAR_GET_CODE_BY(CE.EVENT_CD)
    ,
    CE.CATALOG_CD
    ,
	C_CATALOG_DISP = UAR_GET_CODE_DISPLAY(CE.CATALOG_CD)
	, 
    CE.PERFORMED_DT_TM
	, 
    CE.VIEW_LEVEL
    ,
    PATIENT = E.NAME_FULL_FORMATTED
	,
    P_ID = E.PERSON_ID
	,
    ADMIT = NULLVAL(E.ARRIVE_DT_TM,E.REG_DT_TM) "@SHORTDATETIME"
	,
    DEPART = NULLVAL(E.DEPART_DT_TM,E.DISCH_DT_TM) "@SHORTDATETIME"
	,
    ENCNTR_DATES = 
        CONCAT(
  		    IF (NULLIND(E.ARRIVE_DT_TM)=1) FORMAT(E.REG_DT_TM,"DD/MM/YY HH:MM")
  		    ELSE FORMAT(E.ARRIVE_DT_TM,"DD/MM/YY HH:MM") 
            ENDIF
            ," - ",
            IF(NULLIND(E.DEPART_DT_TM)=1) FORMAT(E.DISCH_DT_TM,"DD/MM/YY HH:MM")
            ELSE FORMAT(E.DEPART_DT_TM,"DD/MM/YY HH:MM") 
            ENDIF
        )
    ,
    SCHEDULTED_TIME = TA.SCHEDULED_DT_TM "DD/MM/YYYY HH:MM"
    ; , 
    ; DOSAGE_UNIT = UAR_GET_CODE_DISPLAY( CEM.DOSAGE_UNIT_CD )
	; , 
    ; ROUTE = UAR_GET_CODE_DISPLAY( CEM.ADMIN_ROUTE_CD )
	, 
    FREQUENCY = UAR_GET_CODE_DISPLAY( FS.FREQUENCY_CD )
	, 
    ORDERED = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
    ,
    O.SIMPLIFIED_DISPLAY_LINE
	, 
    PERFORMED_BY_PERSON = PR.NAME_FULL_FORMATTED

FROM
    ENCOUNTER           E
    ,
    CLINICAL_EVENT		CE
    ,
    TASK_ACTIVITY       TA
    ,
    ORDERS              O
    ; ,
    ; CE_MED_RESULT		CEM
	, 
    TASK_ACTIVITY		TA
	, 
    ENCNTR_ALIAS		EA
	, 
    PERSON			    P
	, 
    PRSNL				PR
	, 
    ORDERS			    O
	, 
    FREQUENCY_SCHEDULE	FS

PLAN E;ENCOUNTER
    WHERE
        E.MED_SERVICE_CD = 313015 ; 'ONCOLOGY' MED SERVICE PATIENTS
        AND (;DEPARTED DATE IS IN THE FUTURE OR NEVER AT ALL
            E.DEPART_DT_TM > CNVTDATETIME(CURDATE, CURTIME3)
            OR
            E.DISCH_DT_TM > CNVTDATETIME(CURDATE, CURTIME3)
            OR 
            (E.DEPART_DT_TM IS NULL AND E.DISCH_DT_TM IS NULL)
        )
        AND (; RECORDED DATE IS TURNED UP IN THE PAST
            E.ARRIVE_DT_TM < CNVTDATETIME(CURDATE, CURTIME3)
            OR
            E.REG_DT_TM < CNVTDATETIME(CURDATE, CURTIME3)
        )
        AND E.ACTIVE_IND = 1 ; ENCOUNTER IS ACTIVE

JOIN CE;CLINICAL_EVENT
    WHERE  CE.ENCNTR_ID = E.ENCNTR_ID

JOIN TA;TASK_ACTIVITY
    WHERE TA.ORDER_ID = CE.ORDER_ID
		AND TA.SCHEDULED_DT_TM != NULL
		AND TA.ACTIVE_IND = 1

JOIN O;ORDERS
    WHERE O.ORDER_ID = CE.ORDER_ID
		AND
        O.ACTIVE_IND = 1

; JOIN    CEM;CE_MED_RESULT
;     WHERE CEM.EVENT_ID = OUTERJOIN(CE.EVENT_ID)

JOIN P;PERSON
    WHERE P.PERSON_ID = E.PERSON_ID
		AND
        P.ACTIVE_IND = 1
		
JOIN PR;PRSNL
    WHERE PR.PERSON_ID = OUTERJOIN(CE.PERFORMED_PRSNL_ID)
		AND
        PR.ACTIVE_IND = OUTERJOIN(1)

JOIN FS;FREQUENCY_SCHEDULE
    WHERE FS.FREQUENCY_ID = OUTERJOIN(O.FREQUENCY_ID)
		AND
        FS.ACTIVE_IND = OUTERJOIN(1)

