SELECT
	P.ACTIVE_IND
	, BEGIN_DATE = P.BEGIN_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, END_DATE = P.END_EFFECTIVE_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, IPASS_DATA_TYPE = UAR_GET_CODE_DISPLAY(P.IPASS_DATA_TYPE_CD)
	, UPDATED = P.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, PC_PCT_MED_SERVICE_DISP = UAR_GET_CODE_DISPLAY(PC.PCT_MED_SERVICE_CD)
	, PC_PCT_ROLE_DISP = UAR_GET_CODE_DISPLAY(PC.PCT_ROLE_CD)
	, PC_PCT_TEAM_DISP = UAR_GET_CODE_DISPLAY(PC.PCT_TEAM_CD)
	, PATIENT_NAME = PE.NAME_FULL_FORMATTED
	, PATIENT_UR_NUMBER = PA.ALIAS
	, STAFF_NAME = PR.NAME_FULL_FORMATTED

FROM
	PCT_IPASS   P
	, PCT_CARE_TEAM   PC
	, PERSON   PE
	, PERSON_ALIAS   PA
	, PRSNL   PR

PLAN P ;PCT_IPASS
	WHERE P.BEGIN_EFFECTIVE_DT_TM > CNVTDATETIME("10-JAN-2022 00:00:00.00")
JOIN PC ; PCT_CARE_TEAM
	WHERE PC.PCT_CARE_TEAM_ID = OUTERJOIN(P.PCT_CARE_TEAM_ID)
JOIN PE ;PERSON
	WHERE PE.PERSON_ID = OUTERJOIN(P.PERSON_ID)
JOIN PA ; PERSON_ALIAS
	WHERE OUTERJOIN(P.PERSON_ID) = PA.PERSON_ID
		AND PA.PERSON_ALIAS_TYPE_CD = OUTERJOIN(10); UR NUMBERS ONLY
        AND PA.ACTIVE_IND = 1 ; ACTIVE ALIAS' (URN) ONLY
JOIN PR ; PRSNL
	WHERE OUTERJOIN(P.LAST_UPDT_PRSNL_ID) = PR.PERSON_ID

WITH MAXREC = 10000000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 120