SELECT
	O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, O.CATALOG_CD
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	, O.DESCRIPTION
	, O.PRIMARY_MNEMONIC
	, O.UPDT_DT_TM
	, O.ACTIVE_IND
	, O_ACTIVITY_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_TYPE_CD)
	, O_ACTIVITY_SUBTYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_SUBTYPE_CD)

FROM
	ORDER_CATALOG   O

WHERE cnvtupper(O.DESCRIPTION) = "*PATIENT HAS EXPERIENCED FOETAL/NEONATAL DEATH*"

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10


SELECT
	COUNT(*)
FROM
	ORDERS
WHERE
	ORDERS.CATALOG_CD = 86328082.00