SELECT
      CATALOG_TYPE = UAR_GET_CODE_DISPLAY(ORDER_CATALOG.CATALOG_TYPE_CD)
    , ACTIVITY_TYPE = UAR_GET_CODE_DISPLAY(ORDER_CATALOG.ACTIVITY_TYPE_CD)
    , PRIMARY_NAME = ORDER_CATALOG.PRIMARY_MNEMONIC
	, PRIMARY_ACTIVE = ORDER_CATALOG_SYNONYM.ACTIVE_IND
    , OE_FORMAT = ORDER_ENTRY_FORMAT.OE_FORMAT_NAME

FROM
    ORDER_CATALOG
    , ORDER_CATALOG_SYNONYM
    , ORDER_ENTRY_FORMAT

PLAN ORDER_CATALOG
    WHERE
        ORDER_CATALOG.CATALOG_TYPE_CD = 77902618.00     ; Referral

JOIN ORDER_CATALOG_SYNONYM
    WHERE
        ORDER_CATALOG_SYNONYM.CATALOG_CD = ORDER_CATALOG.CATALOG_CD
        AND
        ORDER_CATALOG_SYNONYM.MNEMONIC_TYPE_CD = 2583   ; Code value for 'primary' from code set 6011
JOIN ORDER_ENTRY_FORMAT
    WHERE ORDER_ENTRY_FORMAT.OE_FORMAT_ID = ORDER_CATALOG.OE_FORMAT_ID

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME=10