SELECT
    CE.RESULT_VAL ; THIS PULLS WHAT THE DR PUT IN THE FIELD
PLAN
    CLINICAL_EVENT CE
        WHERE
            CE.PERSON_ID = 12345 ; PERSONS ID GOES HERE
            AND
            CE.EVENT_CD = 134666758 ; EVENT_CD FOR THE FIELD GOES HERE, THIS ONE IS THE 'CONSULTANT' IN B2031

JOIN
    PERSON P
    WHERE P.PERSON_ID = 12345 ; PERSONS ID GOES HERE
WITH

; ID of test user    14126208