SELECT
    CURRENT_ORDER_STATUS = UAR_GET_CODE_DISPLAY(ORDERS.ORDER_STATUS_CD)
FROM
    ORDER_ACTION
    , ORDERS
PLAN ORDERS
    WHERE
        ORDERS.ORIG_ORDER_DT_TM BETWEEN CNVTDATETIME("04-MAR-2023") AND CNVTDATETIME("5-MAR-2023")
JOIN ORDER_ACTION
    WHERE
        ORDER_ACTION.ORDER_ID = ORDERS.ORDER_ID
        AND
        ORDER_ACTION.ACTION_TYPE_CD = 2534	;RADIOLOGY ORDERS ONLY
WITH
    TIME = 10