SELECT
	C.ACCESSION_NBR
	, C.AUTHENTIC_FLAG
	, C_CATALOG_DISP = UAR_GET_CODE_DISPLAY(C.CATALOG_CD)
	, C.CE_DYNAMIC_LABEL_ID
	, C.CE_GROUPING_ID
	, C.CLINICAL_EVENT_ID
	, C.CLINICAL_SEQ
	, C.CLINSIG_UPDT_DT_TM
	, C.COLLATING_SEQ
	, C_CONTRIBUTOR_SYSTEM_DISP = UAR_GET_CODE_DISPLAY(C.CONTRIBUTOR_SYSTEM_CD)
	, C.CRITICAL_HIGH
	, C.CRITICAL_LOW
	, C.DEVICE_FREE_TXT
	, C.ENCNTR_FINANCIAL_ID
	, C.ENCNTR_ID
	, C_ENTRY_MODE_DISP = UAR_GET_CODE_DISPLAY(C.ENTRY_MODE_CD)
	, C_EVENT_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_CD)
	, C_EVENT_CLASS_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_CLASS_CD)
	, C.EVENT_END_DT_TM
	, C.EVENT_END_DT_TM_OS
	, C.EVENT_END_TZ
	, C.EVENT_ID
	, C_EVENT_RELTN_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_RELTN_CD)
	, C.EVENT_START_DT_TM
	, C.EVENT_START_TZ
	, C.EVENT_TAG
	, C.EVENT_TAG_SET_FLAG
	, C.EVENT_TITLE_TEXT
	, C.EXPIRATION_DT_TM
	, C_INQUIRE_SECURITY_DISP = UAR_GET_CODE_DISPLAY(C.INQUIRE_SECURITY_CD)
	, C.MODIFIER_LONG_TEXT_ID
	, C.NOMEN_STRING_FLAG
	, C_NORMALCY_DISP = UAR_GET_CODE_DISPLAY(C.NORMALCY_CD)
	, C_NORMALCY_METHOD_DISP = UAR_GET_CODE_DISPLAY(C.NORMALCY_METHOD_CD)
	, C.NORMAL_HIGH
	, C.NORMAL_LOW
	, C.NORMAL_REF_RANGE_TXT
	, C.NOTE_IMPORTANCE_BIT_MAP
	, C.ORDER_ACTION_SEQUENCE
	, C.ORDER_ID
	, C.PARENT_EVENT_ID
	, C.PERFORMED_DT_TM
	, C.PERFORMED_PRSNL_ID
	, C.PERFORMED_TZ
	, C.PERSON_ID
	, C.PUBLISH_FLAG
	, C_QC_REVIEW_DISP = UAR_GET_CODE_DISPLAY(C.QC_REVIEW_CD)
	, C_RECORD_STATUS_DISP = UAR_GET_CODE_DISPLAY(C.RECORD_STATUS_CD)
	, C.REFERENCE_NBR
	, C_RESOURCE_DISP = UAR_GET_CODE_DISPLAY(C.RESOURCE_CD)
	, C_RESOURCE_GROUP_DISP = UAR_GET_CODE_DISPLAY(C.RESOURCE_GROUP_CD)
	, C_RESULT_STATUS_DISP = UAR_GET_CODE_DISPLAY(C.RESULT_STATUS_CD)
	, C_RESULT_TIME_UNITS_DISP = UAR_GET_CODE_DISPLAY(C.RESULT_TIME_UNITS_CD)
	, C_RESULT_UNITS_DISP = UAR_GET_CODE_DISPLAY(C.RESULT_UNITS_CD)
	, C.RESULT_VAL
	, C.ROWID
	, C.SERIES_REF_NBR
	, C_SOURCE_DISP = UAR_GET_CODE_DISPLAY(C.SOURCE_CD)
	, C.SRC_CLINSIG_UPDT_DT_TM
	, C.SRC_EVENT_ID
	, C.SUBTABLE_BIT_MAP
	, C_TASK_ASSAY_DISP = UAR_GET_CODE_DISPLAY(C.TASK_ASSAY_CD)
	, C.TASK_ASSAY_VERSION_NBR
	, C.TRAIT_BIT_MAP
	, C.UPDT_APPLCTX
	, C.UPDT_CNT
	, C.UPDT_DT_TM
	, C.UPDT_ID
	, C.UPDT_TASK
	, C.VALID_FROM_DT_TM
	, C.VALID_UNTIL_DT_TM
	, C.VERIFIED_DT_TM
	, C.VERIFIED_PRSNL_ID
	, C.VERIFIED_TZ
	, C.VIEW_LEVEL

FROM
	CLINICAL_EVENT   C_E

SELECT
	O.ABN_REVIEW_IND
	, O.ACTIVE_IND
	, O_ACTIVITY_SUBTYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_SUBTYPE_CD)
	, O_ACTIVITY_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_TYPE_CD)
	, O.AUTO_CANCEL_IND
	, O.BILL_ONLY_IND
	, O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	, O.CKI
	, O.COMMENT_TEMPLATE_FLAG
	, O.COMPLETE_UPON_ORDER_IND
	, O.CONCEPT_CKI
	, O_CONSENT_FORM_FORMAT_DISP = UAR_GET_CODE_DISPLAY(O.CONSENT_FORM_FORMAT_CD)
	, O.CONSENT_FORM_IND
	, O_CONSENT_FORM_ROUTING_DISP = UAR_GET_CODE_DISPLAY(O.CONSENT_FORM_ROUTING_CD)
	, O.CONT_ORDER_METHOD_FLAG
	, O_CS_INDEX_DISP = UAR_GET_CODE_DISPLAY(O.CS_INDEX_CD)
	, O_DCP_CLIN_CAT_DISP = UAR_GET_CODE_DISPLAY(O.DCP_CLIN_CAT_CD)
	, O.DC_DISPLAY_DAYS
	, O.DC_INTERACTION_DAYS
	, O.DEPT_DISPLAY_NAME
	, O.DEPT_DUP_CHECK_IND
	, O.DESCRIPTION
	, O.DISABLE_ORDER_COMMENT_IND
	, O.DISCERN_AUTO_VERIFY_FLAG
	, O.DOSING_ACT_INGRED_CODE
	, O.DOSING_ALL_INGRED_IND
	, O.DUP_CHECKING_IND
	, O_EVENT_DISP = UAR_GET_CODE_DISPLAY(O.EVENT_CD)
	, O.FORM_ID
	, O.FORM_LEVEL
	, O.IC_AUTO_VERIFY_FLAG
	, O.INST_RESTRICTION_IND
	, O.MODIFIABLE_FLAG
	, O.OE_FORMAT_ID
	, O.OP_DC_DISPLAY_DAYS
	, O.OP_DC_INTERACTION_DAYS
	, O.ORDERABLE_TYPE_FLAG
	, O.ORDER_REVIEW_IND
	, O.ORD_COM_TEMPLATE_LONG_TEXT_ID
	, O.PREP_INFO_FLAG
	, O.PRIMARY_MNEMONIC
	, O.PRINT_REQ_IND
	, O.PROMPT_IND
	, O.QUICK_CHART_IND
	, O.REF_TEXT_MASK
	, O_REQUISITION_FORMAT_DISP = UAR_GET_CODE_DISPLAY(O.REQUISITION_FORMAT_CD)
	, O_REQUISITION_ROUTING_DISP = UAR_GET_CODE_DISPLAY(O.REQUISITION_ROUTING_CD)
	, O_RESOURCE_ROUTE_DISP = UAR_GET_CODE_DISPLAY(O.RESOURCE_ROUTE_CD)
	, O.RESOURCE_ROUTE_LVL
	, O.REVIEW_HIERARCHY_ID
	, O.ROWID
	, O.SCHEDULE_IND
	, O.SOURCE_VOCAB_IDENT
	, O.SOURCE_VOCAB_MEAN
	, O.STOP_DURATION
	, O_STOP_DURATION_UNIT_DISP = UAR_GET_CODE_DISPLAY(O.STOP_DURATION_UNIT_CD)
	, O_STOP_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.STOP_TYPE_CD)
	, O.UPDT_APPLCTX
	, O.UPDT_CNT
	, O.UPDT_DT_TM
	, O.UPDT_ID
	, O.UPDT_TASK
	, O.VETTING_APPROVAL_FLAG

FROM
	ORDER_CATALOG   O_C
