SELECT
	 C_CATALOG_DISP = UAR_GET_CODE_DISPLAY(C.CATALOG_CD)
	, C.CLINICAL_EVENT_ID
	, C.ENCNTR_ID
	, C_EVENT_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_CD)
	, C_EVENT_CLASS_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_CLASS_CD)
	, C_EVENT_RELTN_DISP = UAR_GET_CODE_DISPLAY(C.EVENT_RELTN_CD)
	, C.EVENT_TITLE_TEXT
	, C.PARENT_EVENT_ID
	, C.RESULT_VAL
	, C_SOURCE_DISP = UAR_GET_CODE_DISPLAY(C.SOURCE_CD)
	, C_TASK_ASSAY_DISP = UAR_GET_CODE_DISPLAY(C.TASK_ASSAY_CD)

FROM
	CLINICAL_EVENT   C

WHERE
	C.EVENT_START_DT_TM >= CNVTDATETIME("31-FEB-2021 00:00:00.00")
	AND
	C.EVENT_START_DT_TM <= CNVTDATETIME("31-JUL-2021 23:59:59.00")

WITH MAXREC = 5000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 300