SELECT
;   MAPE.BAR_CODE_IDENT
;   , MAPE.EXPECTED_PT_ID
;   , MAPE.FREETEXT_REASON
;   , MAPE.IDENTIFIED_PT_ID
;   , MAPE.MED_ADMIN_ALERT_ID
;   , MAPE.MED_ADMIN_PT_ERROR_ID
     MAPE_REASON_DISP = UAR_GET_CODE_DISPLAY(MAPE.REASON_CD)
;   , MAPE.ROWID
;   , MAPE.UPDT_APPLCTX
;   , MAPE.UPDT_CNT
;   , MAPE.UPDT_DT_TM
;   , MAPE.UPDT_ID
;   , MAPE.UPDT_TASK
    , DT_COMPLETED = MAPE.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
    , DT_COMPLETED_YEAR = MAPE.UPDT_DT_TM "YYYY;;D"
    , DT_COMPLETED_MONTH = MAPE.UPDT_DT_TM "MM;;D"
    , DT_COMPLETED_DAY = MAPE.UPDT_DT_TM "DD;;D"
    , DT_COMPLETED_TIME = MAPE.UPDT_DT_TM "HH:MM:SS;;D"

FROM
    MED_ADMIN_PT_ERROR   MAPE

WHERE 
    MAPE.UPDT_DT_TM
    BETWEEN
    CNVTDATETIME("01-JUL-2022 00:00:00.00")
    AND
    CNVTDATETIME("01-SEP-2022 00:00:00.00")

WITH NOCOUNTER, SEPARATOR=" ", FORMAT
