SELECT
	DT_COMPLETED = M.UPDT_DT_TM "YYYY-MM-DD HH:MM:SS;;D"
	, DT_COMPLETED_YEAR = M.UPDT_DT_TM "YYYY;;D"
	, DT_COMPLETED_MONTH = M.UPDT_DT_TM "MM;;D"
	, DT_COMPLETED_DAY = M.UPDT_DT_TM "DD;;D"
	, DT_COMPLETED_TIME = M.UPDT_DT_TM "HH:MM:SS;;D"
	, M.BAR_CODE_IDENT
	, M.EXPECTED_PT_ID
	, M.FREETEXT_REASON
	, M.IDENTIFIED_PT_ID
	, M.MED_ADMIN_ALERT_ID
	, M.MED_ADMIN_PT_ERROR_ID
	, M_REASON_DISP = UAR_GET_CODE_DISPLAY(M.REASON_CD)
	, M.ROWID
	, M.UPDT_APPLCTX
	, M.UPDT_CNT
	, M.UPDT_DT_TM
	, M.UPDT_ID
	, M.UPDT_TASK

FROM
	MED_ADMIN_PT_ERROR   M

WHERE 
	M.UPDT_DT_TM
	BETWEEN
		CNVTDATETIME("01-DEC-2022 00:00:00.00")
 		AND
 		CNVTDATETIME("02-DEC-2022 00:00:00.00")

ORDER BY
	DT_COMPLETED   DESC

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, time = 10