SELECT
	O.ENCNTR_ID
	, O.ORDER_ID
	, O.ORIG_ORDER_DT_TM
	, P.NAME_FULL_FORMATTED
	, O.ORDERED_AS_MNEMONIC
	, O.ORDER_DETAIL_DISPLAY_LINE
	, OD.OE_FIELD_DISPLAY_VALUE
	, O.ORDER_MNEMONIC

FROM
	ORDERS   O
	, (LEFT JOIN PERSON P ON (P.PERSON_ID = O.PERSON_ID))
	, (INNER JOIN ORDER_DETAIL OD ON (OD.ORDER_ID = O.ORDER_ID) AND OD.oe_field_meaning = "DIETARYMODIFIERS")

PLAN O
WHERE 
	O.ORIG_ORDER_DT_TM > CNVTLOOKBEHIND("40,D")
	AND
	O.CATALOG_CD = 105460833 ; Diet Orders Only
;	AND
;	OD.oe_field_id IN(656367, 82850080, 82850109, 82850113, 82850116, 87997241) ; Field Id's for dietry modifiers
;	OD.oe_field_meaning = "DIETARYMODIFIERS"
	
JOIN P
JOIN OD

WITH MAXREC = 100, NOCOUNTER, SEPARATOR=" ", FORMAT