SELECT
	O_ACTIVITY_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_TYPE_CD)
	, O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	, O.ENCNTR_ID
	, O.ORDER_ID
	, O.PERSON_ID
	, O.ORIG_ORDER_DT_TM
	, P.NAME_FULL_FORMATTED

FROM
	ORDERS   O
	, (LEFT JOIN PERSON P ON (P.PERSON_ID = O.PERSON_ID))

WHERE 
	O.ORIG_ORDER_DT_TM > CNVTLOOKBEHIND("50,D")
	AND
	O.CATALOG_CD = 105460833 ; Diet Orders Only

WITH MAXREC = 5000, NOCOUNTER, SEPARATOR=" ", FORMAT
