SELECT
	O.ENCNTR_ID
	, O.ORDER_ID
	, O.ORIG_ORDER_DT_TM
	, P.NAME_FULL_FORMATTED
	, OD.OE_FIELD_DISPLAY_VALUE

FROM
	ORDERS   O
	, (LEFT JOIN PERSON P ON (P.PERSON_ID = O.PERSON_ID))
	, (INNER JOIN ORDER_DETAIL OD ON (OD.ORDER_ID = O.ORDER_ID) 
		AND OD.oe_field_meaning = "DIETARYMODIFIERS")

PLAN O
WHERE 
	O.ORIG_ORDER_DT_TM > CNVTLOOKBEHIND("35,D") ; Timeline filter
	AND
	O.CATALOG_CD = 105460833 ; Diet Orders Only
	
JOIN P
JOIN OD

WITH 
	MAXREC = 50,
	NOCOUNTER, 
	SEPARATOR=" ",
	FORMAT