SELECT
	C_CATALOG_DISP = UAR_GET_CODE_DISPLAY(C.CATALOG_CD)
	, C.PERSON_ID
	, C.RESULT_VAL
	, C.UPDT_DT_TM
	, P.NAME_FULL_FORMATTED

FROM
	CLINICAL_EVENT   C
	, (LEFT JOIN PERSON P ON (C.PERSON_ID = P.PERSON_ID))
	
PLAN C

WHERE
;	C.UPDT_DT_TM > CNVTLOOKBEHIND("35,D")
;	AND
	C.event_cd = 86163053 ; Filters for MST Score
	
JOIN P

WITH MAXREC = 500, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10