SELECT
	CV1.DISPLAY_KEY
	, CV1.CODE_SET
	, CV1.CODE_VALUE
	, CV1.DISPLAY
	, CV1.DESCRIPTION
	, CV1.DEFINITION

FROM
	CODE_VALUE   CV1

WHERE CV1.DISPLAY_KEY = "MSTSCORE"

WITH MAXREC = 100, NOCOUNTER
	, SEPARATOR=" ", FORMAT
	, TIME = 10