drop program wh_my_orders go
create program wh_my_orders

prompt
	"Output to File/Printer/MINE" = "MINE"   ;* Enter or select the printer or file name to send this report to.
	, "Ordered After:" = "SYSDATE"
	, "Ordered Before" = "SYSDATE"

with OUTDEV, ORDERED_AFTER, ORDERED_BEFORE

SELECT DISTINCT INTO $OUTDEV
	ACTIONER = PR.USERNAME
	, ORDER_DATE = OA.ORDER_DT_TM "DD-MMM-YYYY"
	, ORDER_TIME = OA.ORDER_DT_TM "HH:MM:SS;;D"
	, ORDER_STATUS = UAR_GET_CODE_DISPLAY(O.ORDER_STATUS_CD)
	, FACILITY = IF(ELH.LOC_FACILITY_CD > 0) UAR_GET_CODE_DISPLAY(ELH.LOC_FACILITY_CD)
        ELSE UAR_GET_CODE_DISPLAY(E.LOC_FACILITY_CD)
        ENDIF
	, NURSE_UNIT = IF(ELH.LOC_NURSE_UNIT_CD > 0) UAR_GET_CODE_DISPLAY(ELH.LOC_NURSE_UNIT_CD)
        ELSE UAR_GET_CODE_DISPLAY(E.LOC_NURSE_UNIT_CD)
        ENDIF
	, O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(OCS.CATALOG_CD)
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(OCS.CATALOG_TYPE_CD)
	, ACTIVITY_TYPE = UAR_GET_CODE_DISPLAY(OCS.ACTIVITY_TYPE_CD)
	, OCS.MNEMONIC
	, MNEMONIC_TYPE = UAR_GET_CODE_DISPLAY(OCS.MNEMONIC_TYPE_CD)
	, PATIENT_URN = PA.ALIAS
	, E.ENCNTR_ID

FROM
	ORDER_ACTION   OA
	, PRSNL   PR
	, ORDER_CATALOG_SYNONYM   OCS
	, ORDERS   O
	, ENCOUNTER   E
	, ENCNTR_LOC_HIST   ELH	;ENCNTR_LOC_HIST
	, PERSON_ALIAS   PA

PLAN OA;ORDER_ACTION
    WHERE
		OA.ACTION_TYPE_CD = OUTERJOIN(2534.00);Order
		AND OA.ACTION_PERSONNEL_ID = REQINFO->UPDT_ID
		AND OA.ACTION_DT_TM > OUTERJOIN(CNVTDATETIME($ORDERED_AFTER))
		AND OA.ACTION_DT_TM < OUTERJOIN(CNVTDATETIME($ORDERED_BEFORE))

JOIN PR;PRSNL
    WHERE
        PR.PERSON_ID = OUTERJOIN(OA.ACTION_PERSONNEL_ID)
        AND PR.ACTIVE_IND = OUTERJOIN(1)
        AND PR.END_EFFECTIVE_DT_TM > OUTERJOIN(SYSDATE)

JOIN OCS
	WHERE OCS.SYNONYM_ID = OA.SYNONYM_ID

JOIN O
	WHERE O.ORDER_ID = OA.ORDER_ID
	AND O.ACTIVE_IND = 1

JOIN PA
	WHERE
		PA.PERSON_ID = OUTERJOIN(O.PERSON_ID)
		AND PA.ACTIVE_IND = OUTERJOIN(1)
		AND PA.END_EFFECTIVE_DT_TM > OUTERJOIN(SYSDATE)
		AND PA.ALIAS_POOL_CD = OUTERJOIN(9569589.00) ; URN POOL CODE

JOIN E ;ENCOUNTER ; To get encounter details
    WHERE
        E.ENCNTR_ID = O.ENCNTR_ID
        AND E.ACTIVE_IND = 1

JOIN ELH ;ENCNTR_LOC_HIST
    WHERE ELH.ENCNTR_ID = OUTERJOIN(O.ENCNTR_ID)
    AND ELH.ACTIVE_IND = OUTERJOIN(1)   ; to remove inactive rows that seem to appear for unknown reason(s)
    AND ELH.PM_HIST_TRACKING_ID > OUTERJOIN(0)  ; to remove duplicate row that seems to occur at discharge
    AND ELH.BEG_EFFECTIVE_DT_TM < OUTERJOIN(O.ORIG_ORDER_DT_TM) ; encounter location began before order was placed
    AND ELH.END_EFFECTIVE_DT_TM >  OUTERJOIN(O.ORIG_ORDER_DT_TM)    ; encounter location ended after order was placed

WITH NOCOUNTER, SEPARATOR=" ", FORMAT, time = 60

end
go