SELECT
	O.ORIG_ORDER_DT_TM
	, STAFF = PR.NAME_FULL_FORMATTED
	, PATIENT = P.NAME_FULL_FORMATTED
	, AH_ORDER_FLAG = EVALUATE(
		O.AD_HOC_ORDER_FLAG,
		0,"Not ad hoc",
		1,"Ad hoc via Bridge Interface",
		2,"Ad hoc with completed order and task via Cerner Solutions",
		3,"Adhoc Order with pending task and order in ordered status vi"
		)
	, O_CATALOG_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_CD)
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	, O.ORDER_MNEMONIC
	, O.ORDERED_AS_MNEMONIC

FROM
	ORDERS   O
	, PERSON   P
	, PRSNL   PR

PLAN O
	WHERE O.UPDT_ID IN (11659304,13975953); Ann and Adrain

JOIN P WHERE P.PERSON_ID = O.PERSON_ID
JOIN PR WHERE PR.PERSON_ID = O.UPDT_ID

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 30