SELECT
	URN = PA.ALIAS
	, E.PERSON_ID
	, E.ENCNTR_ID
	, E_ENCNTR_STATUS_DISP = UAR_GET_CODE_DISPLAY(E.ENCNTR_STATUS_CD)
	, E.EST_ARRIVE_DT_TM
	, E.EST_DEPART_DT_TM

FROM
	ENCOUNTER   E
	, (LEFT JOIN PERSON_ALIAS PA ON PA.PERSON_ID = E.PERSON_ID)

PLAN
	E
	
JOIN
	PA
		WHERE
			PA.ALIAS = "XXXXXX" ; Enter the patients URN here

;WHERE

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT
