SELECT
/*
NOTES
2516.00 = "Pharmacy" in TASK_ACTIVITY.CATALOG_TYPE_CD
 */
	T.ACTIVE_IND
	, T_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(T.CATALOG_TYPE_CD)
	, T_CATALOG_DISP = UAR_GET_CODE_DISPLAY(T.CATALOG_CD)
	, T_LOCATION_DISP = UAR_GET_CODE_DISPLAY(T.LOCATION_CD)
	, T_LOC_BED_DISP = UAR_GET_CODE_DISPLAY(T.LOC_BED_CD)
	, T.SCHEDULED_DT_TM
	, T.COMMENTS
	, T.MESSAGE_TXT
	, T.MSG_SUBJECT
	, T.SOURCE_TAG
	, T_TASK_ACTIVITY_DISP = UAR_GET_CODE_DISPLAY(T.TASK_ACTIVITY_CD)
	, T_TASK_ACTIVITY_CLASS_DISP = UAR_GET_CODE_DISPLAY(T.TASK_ACTIVITY_CLASS_CD)
	, T_TASK_STATUS_DISP = UAR_GET_CODE_DISPLAY(T.TASK_STATUS_CD)
	, T_TASK_TYPE_DISP = UAR_GET_CODE_DISPLAY(T.TASK_TYPE_CD)

FROM
	TASK_ACTIVITY   T

WHERE 

    (T.SCHEDULED_DT_TM BETWEEN
        
	    CNVTLOOKBEHIND("1,H")
	    AND
	    CNVTLOOKAHEAD("2,D")
    )
    AND
    T.CATALOG_TYPE_CD = 2516; Pharmacy

WITH MAXREC = 1000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10