SELECT
*
FROM
	PERSON   P
	, (
		(SELECT
			X.PERSON_ID

		FROM
			PERSON   X

		WHERE X.NAME_LAST_KEY = (SELECT PR.NAME_LAST FROM PRSNL PR  WHERE PR.NAME_LAST = "TESTWHS")

		WITH SQLTYPE("F8"))   I
	)

PLAN P
JOIN I WHERE I.PERSON_ID = P.PERSON_ID

WITH MAXREC = 100, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 10