SELECT
	P.USERNAME
	, O.ORIG_ORDER_DT_TM
	, O_ACTIVITY_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.ACTIVITY_TYPE_CD)
	, O_CATALOG_TYPE_DISP = UAR_GET_CODE_DISPLAY(O.CATALOG_TYPE_CD)
	, O.ORDERED_AS_MNEMONIC
	, O.ORDER_DETAIL_DISPLAY_LINE
	, PE.NAME_FULL_FORMATTED

FROM
	ORDERS   O
	, ENCOUNTER   E
	, PRSNL   P
	, PERSON   PE

PLAN O
	WHERE O.ORIG_ORDER_DT_TM
	;< CNVTLOOKBEHIND("10, H")
	BETWEEN
        ; Choose dates below
		CNVTDATETIME("06-JUN-2022 04:30:00.00")
   		AND
   		CNVTDATETIME("08-JUL-2022 09:30:00:.00")


JOIN P WHERE O.UPDT_ID = P.PERSON_ID
	AND P.USERNAME = "USERNAME" ; Person making the order choose user

JOIN E WHERE E.ENCNTR_ID = O.ENCNTR_ID

JOIN PE WHERE PE.PERSON_ID = E.PERSON_ID

ORDER BY
	O.ORIG_ORDER_DT_TM   DESC ; Newest orders first

WITH MAXREC = 50000, NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 30