UPDATE INTO NOMENCLATURE   N
SET
    N.ACTIVE_IND = 1
	, N.ACTIVE_STATUS_CD
	, N.ACTIVE_STATUS_DT_TM
	, N.ACTIVE_STATUS_PRSNL_ID
	, N.BEG_EFFECTIVE_DT_TM
	, N.CMTI
	, N.CONCEPT_CKI
	, N.CONCEPT_IDENTIFIER
	, N.CONCEPT_SOURCE_CD
	, N.CONTRIBUTOR_SYSTEM_CD
	, N.DATA_STATUS_CD
	, N.DATA_STATUS_DT_TM
	, N.DATA_STATUS_PRSNL_ID
	, N.DISALLOWED_IND
	, N.END_EFFECTIVE_DT_TM
	, N.LANGUAGE_CD
	, N.LAST_UTC_TS
	, N.MNEMONIC
	, N.NOMENCLATURE_ID
	, N.NOM_VER_GRP_ID
	, N.PRIMARY_CTERM_IND
	, N.PRIMARY_VTERM_IND
	, N.PRINCIPLE_TYPE_CD
	, N.ROWID
	, N.SHORT_STRING
	, N.SOURCE_IDENTIFIER
	, N.SOURCE_IDENTIFIER_KEYCAP
	, N.SOURCE_STRING
	, N.SOURCE_STRING_KEYCAP
	, N.SOURCE_STRING_KEYCAP_A_NLS
	, N.SOURCE_VOCABULARY_CD
	, N.STRING_IDENTIFIER
	, N.STRING_SOURCE_CD
	, N.STRING_STATUS_CD
	, N.TERM_ID
	, N.UPDT_APPLCTX
	, N.UPDT_CNT
	, N.UPDT_DT_TM
	, N.UPDT_ID
	, N.UPDT_TASK
	, N.VOCAB_AXIS_CD
















    N.END_EFFECTIVE_DT_TM = CNVTDATETIME("31-DEC-2100")
    , N.UPDT_DT_TM = CNVTDATETIME(CURDATE,CURTIME3)
    , P.UPDT_ID = REQINFO->UPDT_ID
    , P.UPDT_CNT = P.UPDT_CNT + 1
WHERE
    N.NOMENCLATURE_ID =
        (
            SELECT
                X. NOMENCLATURE_ID
            FROM
                NOMENCLATURE X
            WHERE
                N.ACTIVE_IND = 0
                ...
                ....
                ....
                TO DO

        )
