SELECT	
    E.PERSON_ID
	, P.NAME_FIRST
	, P.NAME_LAST
	, E.DISCH_DT_TM
	, E_MED_SERVICE_DISP = UAR_GET_CODE_DISPLAY(E.MED_SERVICE_CD)
	
FROM	
	ENCOUNTER   E
	, (LEFT JOIN PERSON P ON (P.PERSON_ID=E.PERSON_ID))
	
WHERE 	
	YEAR(E.DISCH_DT_TM)= 2018 ; Year patients were admitted
	AND
	E.MED_SERVICE_CD IN(86503988,86504539,98615881) ; Med units
	
ORDER BY	
	E.PERSON_ID   DESC
	, E.DISCH_DT_TM   DESC
	
WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 60	
