SELECT
	STAFF_UPDATER = PR.NAME_FULL_FORMATTED
	, PATIENT = PE.NAME_FULL_FORMATTED
	, MED_SERVICE = uar_get_code_display(P.PCT_MED_SERVICE_CD)
	, PATIENT_CARE_TEAM = UAR_GET_CODE_DISPLAY(P.PCT_TEAM_CD)
	, P.BEGIN_EFFECTIVE_DT_TM
	, P.END_EFFECTIVE_DT_TM
	, P.ACTIVE_IND

FROM
	PCT_CARE_TEAM   P
	, PERSON   PE
	, PRSNL   PR
	, DCP_SHIFT_ASSIGNMENT   D

PLAN P			
	WHERE
		P.PCT_TEAM_CD IN (SELECT CODE_VALUE FROM CODE_VALUE WHERE DISPLAY = "*RADU*") ;"Gen Int Med RADU")
		
/*
		P.UPDT_DT_TM
			BETWEEN
			CNVTDATETIME("01-JAN-2022 00:00:00.00") AND 
			CNVTDATETIME("13-JUL-2022 00:00:00.00")
*/

JOIN PR WHERE PR.PERSON_ID = P.UPDT_ID

JOIN D WHERE 
	P.PCT_CARE_TEAM_ID = D.PCT_CARE_TEAM_ID
	AND
	D.UPDT_DT_TM
			BETWEEN
			CNVTDATETIME("01-JUL-2022 00:00:00.00") AND 
			CNVTDATETIME("13-JUL-2022 00:00:00.00")
	
	
			
JOIN PE WHERE D.PERSON_ID = PE.PERSON_ID

WITH MAXREC = 1000, TIME = 10