SELECT
	OEF_ID = OEF.OE_FORMAT_ID
	, OEF_NAME = OEF.OE_FORMAT_NAME
	, OEF_FIELDS.OE_FIELD_ID
	, OEF_FIELDS.LABEL_TEXT
	, OEF_FIELDS.GROUP_SEQ
	, OEF_FIELDS.FIELD_SEQ
	, OEF_FIELDS.ROWID
	, oef.action_type_cd
	, OEF_ACTION_TYPE_DISP = UAR_GET_CODE_DISPLAY(OEF.ACTION_TYPE_CD)

FROM
	ORDER_ENTRY_FORMAT   OEF
	, OE_FORMAT_FIELDS   OEF_FIELDS

PLAN
    OEF ; ORDER_ENTRY_FORMAT
    WHERE OEF.CATALOG_TYPE_CD = 2517 ; Radiology
    AND oef.action_type_cd =        2534.00; Order

JOIN
    OEF_FIELDS ;OE_FORMAT_FIELDS
    WHERE OEF_FIELDS.OE_FORMAT_ID = OEF.OE_FORMAT_ID

ORDER BY
	OEF.OE_FORMAT_NAME
	, OEF_FIELDS.GROUP_SEQ
	, OEF_FIELDS.FIELD_SEQ
	, OEF_FIELDS.ROWID   DESC

WITH TIME = 30