SELECT
	COUNT(CE.EVENT_CD)

FROM
	CLINICAL_EVENT      CE
    ,
    ENCOUNTER           E
	
PLAN CE
    WHERE
	CE.EVENT_CD = 4054683; FBE Result comment
	AND (
		CE.EVENT_END_DT_TM BETWEEN
			CNVTDATETIME("01-JAN-2023 00:00:00.00")
			AND
			CNVTDATETIME("01-JAN-2024 00:00:00.00")
	)

JOIN E
    WHERE E.ENCNTR_ID = CE.ENCNTR_ID
    AND
    E.ENCNTR_TYPE_CD = 309309 ; outpatient encounters


WITH NOCOUNTER, SEPARATOR=" ", FORMAT, TIME = 20

; OUTPUT = 
